### ISSUE TITLE
Событие от Ровера accuracy_position

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#107]
В Событии от Ровера accuracy_position передаётся double[] , где [0]-точность решения в метрах по широте, [1]-точность решения в метрах по долготе, [1]-точность решения в метрах по высоте
А в DemoRoverPluginImplementation передается строка:
EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.accuracy, 10.ToString(), $""));
Нужно генерить double[]

**Comment by ISPLab** [comment]
double[] accurency = new double[] { 0.003, 0.023, 0.002 };
var s_accurency = p8Serializer.SerializeToBase64(accurency);
 EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.accuracy, s_accurency, $""));
