### ISSUE TITLE
Событие sattelites_count от Ровера

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#108]
В Документации https://docs.google.com/document/d/1EBxs96jNLXTjz832dEvYOJYBz3vQeJf4CdsVIXOM5AA/edit#
Событие sattelites_count - это double[4]
Должно быть double[5] для пяти Систем
+Противоречие с кодом в DemoRoverPluginImplementation и при генерации события от Ровера в RoverPostProcessing.cs, там генерится строковое выражение
Нужно прийти к однозначности

**Comment by ISPLab** [comment]
documentation was changed : to 
-- | -- | -- | -- | -- | --
nvlir | rover | sattelites_count | Convert.ToString(int) | содержит информацию об суммарном  количестве доступных спутников для ровера | Pic.1

nvlir | rover | sattelites_desc | String | содержит информацию о количестве доступных спутников GPS, Glonass, Galileo, SSBA Beidou | Pic.1

code change to 
      public const string sattelites_count = "sattelites_count";
        public const string sattelites_desc = "sattelites_desc";
