### ISSUE TITLE
Событие от Ровера rtk_age

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#109]
В событии от Ровера rtk_age (возраст диффпоправок) должны передаваться секунды как double.ToString()
От Ровера приходят, например, значения 0,7 секунды.
DemoRoverPluginImplementation сейчас работает с целыми числами:
int sp= (int)new TimeSpan(0, 0, 13).TotalSeconds;
EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.rtk_age, sp.ToString(), $""));

**Comment by ISPLab** [comment]
change to 
      double rtk_age = 0.34;
                        EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.rtk_age, Convert.ToString(rtk_age), $""));
