### ISSUE TITLE
accuracy_position

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#110]
Ранее решили, что всё что связано с расстояниями передаём в метрах единообразно.
Нужно поправить событие accuracy_position, в котором говорится о мм:
rover | accuracy_position | double[3 | содержит информацию о точности x,y,h в mm
-- | -- | -- | --

**Comment by ISPLab** [comment]
fix
nvlir | rover | accuracy_position | double[3 | содержит информацию о точности x,y,h in meters | Pic.1
-- | -- | -- | -- | -- | --
