### ISSUE TITLE
current_position

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#111]
Нужно определиться с форматом для координат.
Ранее договаривалиь о том, что в current_position передаются радианы,
сейчас прописаны градусы:
rover | current_position | double[3] | содержит информацию о lat,lon,H в формате DS
-- | -- | -- | --
В чём передаём координаты в градусах или в радианах?

**Comment by ISPLab** [comment]
fix 

nvlir | rover | current_position | double[3] | содержит информацию о lat,lon,H (rad,rad, meters) | Pic.1
-- | -- | -- | -- | -- | --

**Comment by kaa1965** [comment]
1. Тогда нужно так же сделать (в радианах) и для усреднённых координат в событии average_position.
2. В документе событие называется average_position в исходниках почему то поправлено на round_position ?

**Comment by kaa1965** [comment]
1. Тогда нужно так же сделать (в радианах) и для усреднённых координат в событии average_position.
2. В документе событие называется average_position в исходниках почему то поправлено на round_position ?

**Comment by ISPLab** [comment]
оставляйте как в демке в документации поправил
