### ISSUE TITLE
Ошибка Десерриализации свойства double[] CoordinatesFixBLH_WGS84 в классе SurveyingResult

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#112]
Ошибка Десерриализации свойства 
public double[] CoordinatesFixBLH_WGS84
в классе SurveyingResult
А именно: 
public double[] CoordinatesFixBLH_WGS84
        {
            get
            {
                var res = this[nameof(CoordinatesFixBLH_WGS84)];
                return res as double[];
            }
            set { this[nameof(CoordinatesFixBLH_WGS84)] = value; }
        }
После десерриализации res является типом «Newtonsoft.Json.Linq.JArray», который не приводится к double[]

  | Name | Value | Type
-- | -- | -- | --
▶ | res | {[ 0.9714344402503744, 0.65519652440418419,   136.26000000000002 ]} | object   {Newtonsoft.Json.Linq.JArray}

**Comment by ISPLab** [comment]
fix
   //Координаты измеренной точки - в BLH-радианы WGS-84
        public double[] CoordinatesFixBLH_WGS84
        {
            get
            {
                var res = this[nameof(CoordinatesFixBLH_WGS84)];
                var ds_res = new P8.Services.Serializing.P8Serializer().DeserializeFromBase64<double[]>(res as string);
                return ds_res;
            }
            set {
                var s_res = new P8.Services.Serializing.P8Serializer().SerializeToBase64(value);
                this[nameof(CoordinatesFixBLH_WGS84)] = s_res; }
        }

![image](https://user-images.githubusercontent.com/8803512/78876211-aa87ee80-7a57-11ea-9418-2fa5a4031090.png)
