### ISSUE TITLE
testdisplatresolution is wrong

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#115]
Windows api 
на планшетах с высоким разрешением физические размеры экрана возвращает неверные

**Comment by ISPLab** [comment]
![FCDCF98E-D7F1-4E28-8125-0BEAFC85F835_1_105_c](https://user-images.githubusercontent.com/8803512/79682443-03f7d680-822b-11ea-8daf-60dfa951bacc.jpeg)

**Comment by kaa1965** [comment]
Такая ситуация возникает из-за драйвера.
Остаётся тогда тот способ, который применяем в критичных для таких ситуациях приложениях, а именно:
1. Рисуем на экране квадрат 300х300 пикселей
2. Пользователь линейкой измеряет ширину и высоту квадрата
3. Пользователь вводит в мм измеренные ширину (X) и высоту(Y) квадрата в соответствующие поля ввода
4. Программа вычисляет размеры пикселя: X/300 и Y/300
5. Сохраняем полученные значения в настройках для последующего применения в Программе

**Comment by ISPLab** [comment]
фишка в том что в разных частях экрана разная плотность пикселей в среднем на винде 96

**Comment by ISPLab** [comment]
при масштабировании это вообще одному гейтсу известно

**Comment by ISPLab** [comment]
винда берет 1280 пикселей для всех мониторов потом своим драйвером дорисовывает с искажениями по цвету и размерам для других масштабов

**Comment by kaa1965** [comment]
![20200420_011644](https://user-images.githubusercontent.com/50620286/79701420-a654a000-82a5-11ea-8825-246a509e7b67.jpg)
Вот на Панасонике всё чётко определяются размеры Panasonic FZ-G1

**Comment by kaa1965** [comment]
![20200420_010706](https://user-images.githubusercontent.com/50620286/79701707-def57900-82a7-11ea-9bac-136815503652.jpg)
А вот так чётко рисуется отрезок в 1 см, получая размеры пикселя через WIN-API, и задавая в пикселях откуда и докуда рисовать отрезок

**Comment by ISPLab** [comment]
Не считая того что линейку сместили на 5мм влево и ещё 2мм не хватает - если программно масштабировать с такими смешениями по вертикали и горизонтали получается месиво

**Comment by ISPLab** [comment]
Отрезок на экране меньше см

**Comment by ISPLab** [comment]
Почитал по этой теме, винда даже не 1280 берет для масштабирования а 800x600, другие графические оболочки (андройд мак иксы) использует не ppi а dpi, в нашем приложении сделал тоже dpi
