### ISSUE TITLE
AliasPolicy

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#117]
На данном этапе разработки функция AliasPolicy расположена в GeoProject.
Эта функция должна переместиться в какую-то другую сущность. Требуется проработать этот вопрос...

**Comment by ISPLab** [comment]
public class AutoSurveyingManager
    {
        IRoverManager roverManager;
        GeoProject project;
        SurveyingParameters parms;
        public AutoSurveyingManager(IRoverManager roverManager,  GeoProject project, SurveyingParameters parms)
        {
            this.roverManager = roverManager;
            this.project = project;
            roverManager.EventPublished += RoverManager_EventPublished;
            this.parms = parms;
            Task.Run(() => Start());
        }

        private void RoverManager_EventPublished(object sender, P8.DomainData.P8EventData e)
        {
            switch (e.ActionName)
            {
                case RoverPluginEvent.surveying_progress:
                    double progress = Convert.ToDouble(e.Parametr);
                    break;

                case RoverPluginEvent.surveying_result:

                    var s_res = new P8Serializer().DeserializeFromBase64<SurveyingResult>(e.Parametr);
                    double[] coord = s_res.CoordinatesFixBLH_WGS84;
                    string des = s_res.ResultDescription;

                    //project.AddsurveyingResult();

                    break;
                default:
                    break;
            }
        }

        public void Start()
        {

            //your logic 
            roverManager.StartSurveying(parms);
        }
    }

**Comment by ISPLab** [comment]
Предлагаю такую (AutoSurveyingManager в хелпере) сущность чтобы и в тестах работала и в ui jlyjdhtvryyj

**Comment by kaa1965** [comment]
1.  NVLirPluginConfiguration работает

2.  Измерения работают

3.  А вот AutoSurveyingManager нужны комментарии. Зачем всё это?

Сейчас есть тесты MakeAutoAverageTest (тест на Автоматическая съёмка С УСРЕДНЕНИЕМ), MakeAutoTest (Автоматическая съёмка без усреднения), MakeManualAverageTest (Ручная съёмка С УСРЕДНЕНИЕМ), MakeManualTest() (Ручная съёмка без усреднения). Все эти тесты вызывают метод Plugina StartSurvey. По мере измерений формируются события stable_antenna, surveying_progress, surveying_result. Обработка этих событий есть в методе Setup() теста

**Comment by ISPLab** [comment]
этот класс нужен для объединения параметров из проекта и кофигурационного файла  и настроек пользовательской интерфейса

**Comment by kaa1965** [comment]
Кто такой IRoverManager? Кто реализует этот интерфейс? Кем создается?
Кто создаёт AutoSurveyingManager? Откуда берёт параметры для его создания?
В любом случае это прикладная логика приложения. К тестам на ручное и автоматическое измерение она не имеет никакого отношения.

**Comment by ISPLab** [comment]
посмотрите тест скорректированный для работы в ui
и если ок делаю коммит    


 public class RoverManagerFake : IRoverManager
    {
        public event EventHandler<P8EventData> EventPublished;

        public void StartSurveying(object param)
        {
            int i = 10;
            while(i<10)
            {
                i++;
                EventPublished?.Invoke(this, new P8EventData("fake_manager", "", "", "",""));
            }
        }

        public void StopSurveying()
        {
          
        }
    }

    [TestFixture()]
    public class AutoSurveyingTest
    {
        [SetUp]
        public void Setup()
        {
          
        }

        [Test]
        public void AutoSurveyingTest()
        {

            P8AutoResetEvent cancell_surveying = new P8AutoResetEvent();
            RoverManagerFake rorver_manager = new RoverManagerFake();
            GeoProject project = new GeoProject();
            SurveyingParameters parms = new SurveyingParameters();
            using (var mock = AutoMock.GetLoose(cfg =>
            {
              cfg.RegisterInstance(rorver_manager).As<IRoverManager>();
              cfg.RegisterInstance(project);
              cfg.RegisterInstance(parms);
            }))
            {
                var dep = mock.Create<IRoverManager>();
                var sut = mock.Create<AutoSurveyingManager>();
                sut.StartSurveying(cancell_surveying);
                System.Threading.Thread.Sleep(5000);
                Assert.AreEqual("expected value", project.surveyingResults.Count>3);
            }
        }
    }

**Comment by ISPLab** [comment]
вариант
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace P8Helper
{
    public sealed class P8AutoResetEvent
    {
        CancellationTokenSource source;
        public bool Result { get; set; }

        public bool IsCancellationRequested
        {
            get
            {
                return source.IsCancellationRequested;
            }
        }
        // Creates an async-compatible auto-reset event.
        public P8AutoResetEvent(bool set = false)
        {
            source = new CancellationTokenSource();
        }
        public CancellationToken GetToken()
        {
            return source.Token;
        }


        public void Reset()
        {
            source?.Cancel();
            source = new CancellationTokenSource();
        }

        // Gets a semi-unique identifier for this asynchronous auto-reset event.
        public int Id { get; }

        // Asynchronously waits for this event to be set.
        // If the event is set, this method will auto-reset it and return immediately, even if the cancellation token is already signalled.
        // If the wait is canceled, then it will not auto-reset this event.
        public async Task<bool> WaitOne(int ms = 0)
        {
            return await Task.Run(() =>
             {
                 Task.WaitAny(new Task[] { WaitCancelAsync(), WaitTimeAsync(ms) });
                 return Result;
             }
            );
        }
        public async Task<bool> WaitTimeAsync(int ms)
        {
            await Task.Delay(ms);
            return Result = false;
        }

        public async Task<bool> WaitCancelAsync()
        {
            return await Task.Run(async () =>
            {
                while (!source.IsCancellationRequested)
                    await Task.Delay(10);
                return Result = true;
            });
        }
  
   

        // Sets the event, atomically completing a task returned by WaitAsync.
        // If the event is already set, this method does nothing.
        public void Set()
        {
            source.Cancel();
        }
    }
}

**Comment by ISPLab** [comment]
using System;
using System.Threading;
using System.Threading.Tasks;
using P8.Services.Serializing;
using P8Helper;
using RoverPluginHelper;

namespace RoverPluginHelper
{
    public class AutoSurveyingManager
    {
        IRoverManager roverManager;
        GeoProject project;
        SurveyingParameters parms;
        public AutoSurveyingManager(IRoverManager roverManager,  GeoProject project, SurveyingParameters parms)
        {
            this.roverManager = roverManager;
            this.project = project;
            roverManager.EventPublished += RoverManager_EventPublished;
            this.parms = parms;
        }

        private void RoverManager_EventPublished(object sender, P8.DomainData.P8EventData e)
        {
            switch (e.ActionName)
            {
                case RoverPluginEvent.surveying_progress:
                    double progress = Convert.ToDouble(e.Parametr);
                    break;

                case RoverPluginEvent.surveying_result:

                    var s_res = new P8Serializer().DeserializeFromBase64<SurveyingResult>(e.Parametr);
                    double[] coord = s_res.CoordinatesFixBLH_WGS84;
                    string des = s_res.ResultDescription;

                    //project.AddsurveyingResult();

                    break;
                default:
                    break;
            }
        }

        public async void StartSurveying(P8AutoResetEvent cancellationToken)
        {
          await Task.Run(async () =>
            {
                var token = cancellationToken.GetToken();
                int quility = 0; //your param
                while (!token.IsCancellationRequested && quility<5) 
                {
                    quility++;
                    await Task.Delay(1000);    //your logic aply alias and ect.
                    roverManager.StartSurveying(parms);
                }
                cancellationToken.Set();
                roverManager.StopSurveying();
            });
        }
    }
}

**Comment by ISPLab** [comment]
Кто такой IRoverManager?
   класс который загружает плагин в тесте и для тестов он предствален 
Кто создаёт AutoSurveyingManager? Откуда берёт параметры для его создания?
Это класс управляет процессом автоматической съемки (измерения)

**Comment by ISPLab** [comment]
Откуда берёт параметры для его создания?
в тесте показано, в ui через ViemModel и DocumentManager

**Comment by kaa1965** [comment]
Что делает roverManager.StartSurveying(parms); ?
зачем цикл с паузой, который пять раз толкает roverManager.StartSurveying(parms); ?

**Comment by ISPLab** [comment]
решение отправлено по почте
