### ISSUE TITLE
ListMountPoints

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#118]
Сейчас при получении списка РС (Точек монтирования) с Сервера результат из плагина на UI  передаётся в виде события configuration_changed. В NVLirPluginConfiguration выставляется и передаётся полученный список с Сервера в виде свойства:
public List<MountPointInfo> ListMountPoints { get; set; }
После того как NVLirPluginConfiguration  унаследован от Dictionary это свойство перестало серриализоваться по шине.
Требуется пример работы с этим свойством-списком.
Тест TurnOnNTRIPListMountPointRoverTest, пример обработки события configuration_changed в Setup() этого теста

**Comment by ISPLab** [comment]
List<T> какого типа?

**Comment by kaa1965** [comment]
List<MountPointInfo>

**Comment by kaa1965** [comment]
Типа MountPointInfo

**Comment by ISPLab** [comment]
проверил на классе 
    public class Desc
    {
        public string Name { get; set; }
        public string Info { get; set; }
    }
    public class DynamicSettigs
    {
        public string Setted { get; set; }
        public List<Desc> desc = new List<Desc>();
        public DynamicSettigs()
        {

        }
    }

**Comment by ISPLab** [comment]
обявляется в  DemoRoverPluginConfig как
        public DynamicSettigs DynamicSettigs
        {
            get
            {
                DynamicSettigs res = null;
                if (this.ContainsKey(nameof(DynamicSettigs)))
                    res = (DynamicSettigs)this[nameof(DynamicSettigs)];
                return (DynamicSettigs)res;
            }
            set
            {
                this[nameof(DynamicSettigs)] = value;
            }
        }

**Comment by ISPLab** [comment]
проблем в таком исполнении не выявлено
