### ISSUE TITLE
definition auto surveying for NVLIRPlugin

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#119]
Автоматический режим для плагина - это ...
Ручной режим для плагина - это ...

**Comment by kaa1965** [comment]
Прежде чем говорить о том, что такое "Автоматический режим для плагина " и "Ручной режим для плагина" нужно говорить о том, что Плагин при получении информации от Ровера может выполнять процедуру усреднения координат + определять факты "стабильности антенны"="факты остановки \ движения". То есть когда Плагин выполняет приём информации от Ровера он параллельно выполняет эти две задачи. Параметры для решения этих задач передаются в TurnOnCommunication в виде параметров:
- NVLirPluginConfiguration.(SurveyingParams as NVlirSurveingParams).IntervalAverageInSec
- NVLirPluginConfiguration.(SurveyingParams as NVlirSurveingParams).MaxAntennaDeviationInM
- NVLirPluginConfiguration.(SurveyingParams as NVlirSurveingParams).UseAverageForFixStartSurvey
То есть когда Пользователь нажимает на кнопку "Измерить" в Ручном режиме Измерения, то Плагин первым делом проверяет:
- есть ли стабильность антенны;
- есть ли усреднённые координаты;
- другие условия (MaxPDOP и др.)
Таким образом, на момент нажатия на кнопку "Измерить" Плагин ничего не ждёт и использует подготовленные в фоновом режиме данные (наличие стабильности антенны и результат усреднения координат).
Ручное Измерение по кнопке "Измерить" - это проверка заданных условий и формирование события surveying_result с результатом Измерения. Причём Результат Измерения может быть с Признаком, что все Условия выполнены, или НЕ выполнены.

Автоматическое Измерение - это запуск фоновой задачи, которая определяет факты движения и остановки. Как только возникает очередная остановка (то есть когда антенна становится стабильной), то проверяются другие Условия. Как только на остановке ВСЕ Условия начинают выполняться, то Плагин формирует события surveying_result с результатом Измерения.

**Comment by ISPLab** [comment]
тогда в autosurveyingmanager достаточно
  public async void StartSurveying(P8AutoResetEvent cancellationToken)
        {
          await Task.Run(async () =>
            {
                parms["AutoSurveing"] = project.AutoSurveying;
                rover.StartSurveying(parms);
            });
        }

**Comment by ISPLab** [comment]
по этому признаку плагину будет достаточно формировать свое поведение от 
"стабильности антенны"

**Comment by kaa1965** [comment]
В приниципе да, мне достаточно при вызове StartSurveying() чтобы я мог откуда то взять признак AutoSurveying = true или false.
