### ISSUE TITLE
AutoSurveyingInitializeTest

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#120]
Для написания тестов на Ручную или Автоматическую съёмку в AutoSurveyingInitializeTest() необходимо:
1. выполнить подключение к Роверу и получать от него информацию, которая и будет измеряться. Подключение к Роверу выполняется в Плагине NVLirPluginImplementation.TurnOnCommunication()
2. Нужно запустить процесс Ручного или Автоматического Измерения, который также расположен в плагине NVLirPluginImplementation.StartSurvey()
3. Для остановки процесса Автоматического Измерения нужно запустить метод, который  расположен в плагине NVLirPluginImplementation.StopSurvey()

Каким образом и откуда выполнять NVLirPluginImplementation.TurnOnCommunication() , NVLirPluginImplementation.StartSurvey() и NVLirPluginImplementation.StopSurvey() при написании теста AutoSurveyingInitializeTest() ?

**Comment by ISPLab** [comment]
1:это модульный  тест для класса autosurveyingmanager, 
подключение/работа к конкректному плагину должно тестироваться в других соответсвующих модульных тестах
2: для ответа необходимо Ваше пояснение что вы понимаете под ручным и автоматическим режимом:
definition auto surveying for NVLIRPlugin #119
3. данный метод находится autosurveyingmanager. Вызывается через UI

**Comment by ISPLab** [comment]
Каким образом и откуда выполнять NVLirPluginImplementation.TurnOnCommunication() , NVLirPluginImplementation.StartSurvey() и NVLirPluginImplementation.StopSurvey() при написании теста AutoSurveyingInitializeTest() ?
При необходимости в своем тесте вы можете добавлять ни FakeRover а свой как это реализовано в других тестах
