### ISSUE TITLE
Именование точек Измерений

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#121]
При вызове StartSurvey() в параметрах передаётся NVlirSurveingParams.
При этом мы говорим о том, что перед вызовом StartSurvey() определяется Ид и Наименование Измерения:
NVlirSurveingParams.Id = Guid.NewGuid()
NVlirSurveingParams.Alias = project.AliasPolicy()
При Ручном Измерении - это нормально. То есть на Момент нажатия на кнопку Id и Alias определить возможно.
Но Проблема с именованием Измерения при Автоматическом режиме.
После вызове StartSurvey() с параметрами для Автоматического Измерения Плагин запускает фоновый процесс в ходе которого автоматически формирует несколько Измерений. Каждому такому Измерению нужно присвоить Id и Alias.
Проблема в том что Плагин не может сформировать Alias для очередного Автоматического Измерения, так как он ничего не знает про GeoProject и не может вызвать project.AliasPolicy()

**Comment by ISPLab** [comment]
плагин может формировать свои гуиды и алиасы
при выдаче surveyingresult берет тот который поступил  на команду Startsurveying(param)

**Comment by kaa1965** [comment]
1. Вызвали у Плагина StartSurvey() с параметрами:
NVlirSurveingParams.AutoModeFix=true;//Автоматическая съёмка 
NVlirSurveingParams.Id = 1
NVlirSurveingParams.Alias = "Point_1"
2. Во время работы в Автоматическом режиме Плагин сформировал первое Измерение, при этом сформировал событие surveying_result  в NVlirPlugSurveyingResult положил полученные Id = 1 и Alias = "Point_1"
3. Дальше Плагин продолжает работать и формирует второе Автоматическое Измерение. **Вопрос: откуда Плагин для этого нового измерения возьмёт новый Id и новый Alias ?**

**Comment by ISPLab** [comment]
сформировал первое Измерение, и сгенерировал tachoresult?
на второе Автоматическое Измерение тоже генерирует tachoresult?

**Comment by kaa1965** [comment]
Пользователь запустил Автоматический режим, ты с UI вызвал StartSurvey() 
Так?

**Comment by ISPLab** [comment]
пользователь выбрал в параметрах проекта автоматический режим и нажал на startsurvying

**Comment by kaa1965** [comment]
Ну нажал, а что ты вызовешь в сторону Плагина? Какой метод?

**Comment by ISPLab** [comment]
public async void StartSurveying(P8AutoResetEvent cancellationToken)
        {
          await Task.Run(async () =>
            {
                ****
                parms["AutoSurveing"] = project.AutoSurveying;
                rover.StartSurveying(parms);
            });
        }

**Comment by ISPLab** [comment]
Можно ли сказать что автоматический режим в контексте плагина - это функция автокоррекции результата?

**Comment by kaa1965** [comment]
A Id и Alias Кто формирует и передаёт в Плагин?

**Comment by ISPLab** [comment]
*** 
  parms.Alias = project.AliasPolicy();

**Comment by ISPLab** [comment]
id само при первом запросе

**Comment by ISPLab** [comment]
сформировал первое Измерение, и сгенерировал tachoresult?
на второе Автоматическое Измерение тоже генерирует tachoresult?

**Comment by kaa1965** [comment]
Не торпись

**Comment by ISPLab** [comment]
Можно ли сказать что автоматический режим в контексте плагина - это функция автокоррекции результата?

**Comment by kaa1965** [comment]
Итак, запустили Плагин, в параметры перед запуском положили:
parms["AutoSurveing"] = project.AutoSurveying;
parms.Alias = project.AliasPolicy();
Плагин сформировал первое Автоматическое Измерение, Сформировал результат, в Результате вернул переданный Id и Alias
Так?

**Comment by ISPLab** [comment]
AutoSurveying было true?

**Comment by kaa1965** [comment]
Да

**Comment by ISPLab** [comment]
сколько сформировал автоматических измерений для того что вернуть результат или может также несколько ?

**Comment by ISPLab** [comment]
сколько сформировал автоматических измерений для того что вернуть результат только одно  или может также несколько ?

**Comment by kaa1965** [comment]
Плагин в Автоматическом режиме формирует сначала одно Измерение и формирует Результат.
Потом Плагин продолжает работать и формирует второе Измерение с другим вторым Результатом. 
Потом Плагин продолжает работать и формирует третье Измерение с другим третьим Результатом. 
И так до тех пор пока не вызовут StopSurvey()

**Comment by ISPLab** [comment]
чем работа плагина отличается с параметром Autosurveying false and true?

**Comment by ISPLab** [comment]
Можно ли сказать что автоматический режим в контексте плагина - это функция автокоррекции результата?

**Comment by kaa1965** [comment]
В Ручном режиме вызвали StartSurvey() c параметром Autosurveying false => Плагин вернёт только один результат.
Плагин в Автоматическом режиме когда вызвали StartSurvey() c параметром Autosurveying True:
формирует сначала одно Измерение и формирует Результат.
Потом Плагин продолжает работать и формирует второе Измерение с другим вторым Результатом.
Потом Плагин продолжает работать и формирует третье Измерение с другим третьим Результатом.
И так до тех пор пока не вызовут StopSurvey()

**Comment by ISPLab** [comment]
чем не устроививает функция в autosurveying manager?
    while (!token.IsCancellationRequested && quility < 5)// 
                   {
                       parms.Alias = project.AliasPolicy();
                       quility++;
                       await Task.Delay(1000);    //your logic aply alias and ect.
                       rover.StartSurveying(parms);
                   }

**Comment by kaa1965** [comment]
Можно ли сказать что автоматический режим в контексте плагина - это функция автокоррекции результата?
Не совсем понимаю, что ты подразумеваешь под термином "функция автокоррекции результата"?
Но ни о какой коррекции предыдущего Измерения речи не идёт.
Плагин в Автоматическом режиме генерит несколько разных Измерений

**Comment by ISPLab** [comment]
чем работа плагина отличается с параметром Autosurveying false and true?

**Comment by ISPLab** [comment]
чем не устроививает функция в autosurveying manager?
while (!token.IsCancellationRequested && quility < 5)//
{
parms.Alias = project.AliasPolicy();
quility++;
await Task.Delay(1000); //your logic aply alias and ect.
rover.StartSurveying(parms);
}

**Comment by kaa1965** [comment]
В Ручном режиме вызвали StartSurvey() c параметром Autosurveying false => Плагин **вернёт только один результат.**
Плагин в Автоматическом режиме когда вызвали StartSurvey() c параметром Autosurveying True **вернёт несколько Результатов**:
формирует сначала одно Измерение и формирует Результат.
Потом Плагин продолжает работать и формирует второе Измерение с другим вторым Результатом.
Потом Плагин продолжает работать и формирует третье Измерение с другим третьим Результатом.
И так до тех пор пока не вызовут StopSurvey()

**Comment by kaa1965** [comment]
В разные моменты времени

**Comment by ISPLab** [comment]
while (!token.IsCancellationRequested )//
{
parms.Alias = project.AliasPolicy();
await //available or your logic aply alias and ect.
rover.StartSurveying(parms);
}

**Comment by ISPLab** [comment]
В разные моменты времени? не понял

**Comment by kaa1965** [comment]
В Ручном режиме вызвали StartSurvey() c параметром Autosurveying false => Плагин вернёт только один результат.
Плагин в Автоматическом режиме когда вызвали StartSurvey() c параметром Autosurveying True вернёт несколько Результатов **в разные моенты времени**:
формирует сначала одно Измерение и формирует Результат.
Потом Плагин продолжает работать и формирует второе Измерение с другим вторым Результатом.
Потом Плагин продолжает работать и формирует третье Измерение с другим третьим Результатом.
И так до тех пор пока не вызовут StopSurvey()

**Comment by kaa1965** [comment]
while (!token.IsCancellationRequested )//
{
parms.Alias = project.AliasPolicy();
await //available or your logic aply alias and ect.
rover.StartSurveying(parms);
}
То есть ты предлагаешь на шине ждать события surveying_result (то есть ждать каждого нового Автоматического Измерения) и потом толкать Плагин для выполнения очередного нового Автоматического Измерения?

**Comment by ISPLab** [comment]
В Ручном режиме вызвали StartSurvey() c параметром Autosurveying false => Плагин вернёт толь.....
Есть ссылка на тз что так надо делать?

**Comment by ISPLab** [comment]
То есть ты предлагаешь на шине ждать события surveying_result (то есть ждать каждого нового Автоматического Измерения) и потом толкать Плагин для выполнения очередного нового Автоматического Измерения?
я думаю  в таком контексте  такое автоматическое измерение лучше никому не показывать

**Comment by kaa1965** [comment]
**ТЗ согласовано с Булавским и Кузьмицким по почте:**
Ручная и Автоматическая съёмки 
Общая часть для функций «Ручная съёмка» и «Автоматическая съёмка»
При приёме координат от Ровера Программа всегда использует «Детектор стопа».
Назначение «Детектора стопа»:
- определять факты «остановка-движение»;
- формировать «готовые» усреднённые координаты на «остановке».
Алгоритмы работы «Детектор стопа»:
При приёме координат от Ровера выполняется вычисление расстояние от новой точки до каждой точки буфера FIFO Детектора. В том случае, если каждое расстояние меньше или равно заданному «Максимальному отклонению антенны» (по умолчанию 3 см), то считается факт Остановки, в противном случае Движение.
В случае Остановки Детектор формирует всегда «Усреднённые координаты», которые используются прикладными задачами (Ручная и Автоматическая съёмка).
Настройки для работы Детектора стопа:
- максимальное отклонение антенны (по умолчанию 3 см);
- интервал усреднения (по умолчанию 5 сек).

Ручная съемка
Предназначена для фиксации измерений по нажатию кнопки «Измерить» Пользователем.
Для выполнения фиксации задаются условия:
- минимальный тип навигационного решения;
- минимальная точность в плане;
- минимальная точность по высоте;
- минимальное количество спутников;
- максимальный PDOP.
Дополнительно для Ручной съёмки определяется режим фиксации:
- без усреднения координат;
- с усреднением координат.
Дополнительно определяются правила именования точек:
- префикс наименования, например: «Точка_»;
- начало нумерации;
- направление нумерации (по возрастанию или по убыванию);
- шаг нумерации (1, 2, …).
При переходе на страницу «Ручная съёмка» Пользователю в текстовом виде отображаются параметры, принимаемые от Ровера с подсветкой на соответствие условиям (используется зелёный-красный цвет).
Полный список отображаемых Параметров в текстовом виде перечислен в ТЗ. Важно отметить то, что отображаются те Параметры, которые проверяются по условиям, и пользователь видит их соответствие (или несоответствие) условиям. 
Пользователю отображается информация о стабильности антенны в виде:
- строки «Антенна стабильна» или «Антенна нестабильна»;
- в виде ползунка.
Ползунок стабильности Антенны отображает в процентном выражении количество точек (из Буфера FIFO Детектора стопа), попавших в зону максимального отклонения антенны (по умолчанию 3 см).
Таким образом Программа всегда предоставляет готовую «Усреднённую точку» по требованию Пользователя без дополнительного ожидания.
Для выполнения измерения Пользователю предоставляется кнопка «Измерить».
После нажатия на кнопку «Измерить» Программа практически сразу предоставляет результат Измерения. При этом проверяется:
- выполнение условий съёмки; 
- стабильность антенны на момент нажатия кнопки (при включенном режиме усреднения). 
Если условия выполняются (и антенна стабильна при включенном режиме усреднения), то:
- присваивает название измеренной точке согласно правилам именования, например: «Точка_1»;
- присваивает «Тип точки Проекта» = «Измеренная»;
-  информирует Пользователя в виде проигрывания звукового сообщения «Ручное измерение выполнено»;
- отображает Диалог «Ручное измерение выполнено, зафиксированы мгновенные координаты» или «Ручное измерение выполнено, зафиксированы усреднённые координаты». В диалоге кнопки «Сохранить», «Отменить». В Диалоге поле ввода для изменения наименования точки;
- после подтверждения Пользователя сохраняет измерение в Проекте: точка (наименование, тип точки, последние координаты или усреднённые в зависимости от режима усреднения), отметка о выполнении условий, условия измерения, исходная информация от Ровера (по сути пакет 0xF1));
Если условия НЕ выполняются (или антенна нестабильна при включенном режиме усреднения), то:
- присваивает название измеренной точке согласно правилам именования, например: «Точка_1»;
- присваивает «Тип точки Проекта» = «Измеренная»;
-  информирует Пользователя в виде проигрывания звукового сообщения «Ручное измерение выполнено с нарушением условий»;
- отображает Диалог «Ручное измерение выполнено с нарушением условий: точность в плане, точность по высоте, геометрический фактор PDOP, количество спутников, тип решения, антенна нестабильна, зафиксированы мгновенные координаты». В диалоге кнопки «Сохранить», «Отменить». В Диалоге поле ввода для изменения наименования точки.
- после подтверждения Пользователя сохраняет измерение в Проекте: точка (наименование, тип точки, последние координаты), отметка о невыполнении условий, условия измерения, исходная информация от Ровера (по сути пакет 0xF1)).
Если на момент фиксации данные от Ровера отсутствуют, Пользователю отображается Диалог: «Ошибка Ручного измерения: нет данных от Ровера» с кнопкой «Закрыть».

Общий вывод по Ручной съёмке:
Ручная съёмка позволяет выполнять измерения всегда (в результате измерения фиксируется выполнены или не выполнены условия съёмки). Фактически Ручная съёмка позволяет фиксировать точки на месте и в движении.
Если усреднение включено, то используется готовая усреднённая точка на момент Измерения, без дополнительного ожидания Пользователем окончания дополнительного процесса усреднения.
Если усреднение включено и на интервале усреднения было критичное отклонение антенны, то зафиксировать измерение можно только с последними известными координатами.

**Comment by ISPLab** [comment]
То есть ты предлагаешь на шине ждать события surveying_result (то есть ждать каждого нового Автоматического Измерения) и потом толкать Плагин для выполнения очередного нового Автоматического Измерения? 
Это противоречит тому о чем вы договаривались в переписках?

**Comment by ISPLab** [comment]
То есть ты предлагаешь на шине ждать события surveying_result (то есть ждать каждого нового Автоматического Измерения) и потом толкать Плагин для выполнения очередного нового Автоматического Измерения?
с точки  зрения смысла в который вы вложили в автоматический режим и ui разницы нет. C точки зрения архитектуры кроссплатформенного приложения другого варианта не вижу

**Comment by kaa1965** [comment]
Итак, правильно я понимаю, что делаем так:
1. При Ручном Измерении при каждом нажатии на кнопку Измерить вызывается StartSurvey() с Autosurveying false. Плагин выполняет одно Измерение. Обработчик события surveying_result, приняв это событие добавляет точку в Проект.
2. При Автоматическом Измерении при нажатии на кнопку Измерить вызывается StartSurvey() с Autosurveying true. **Плагин также выполняет одно Измерение**. Обработчик события surveying_result, приняв это событие добавляет точку в Проект **+ повторно вызывает StartSurvey() с Autosurveying true**

**Так делаем???**

**Comment by ISPLab** [comment]
я так понимаю что Autosurveying в списках параметрах плагину не нужно передавать

**Comment by kaa1965** [comment]
Нужно.
При ручном режиме Плагин вернёт сразу Измерение, которое может не удовлетворять заданным условиям.
При Автоматическом режиме Плагин будет ждать пока не будет антенна стабильна и выполняться все другие условия, и только тогда сформирует Измерение.

**Comment by ISPLab** [comment]
Можно ли сказать что автоматический режим в контексте плагина - это функция автокоррекции результата?

**Comment by kaa1965** [comment]
Нет нельзя.
Автоматический режим никакие результаты не корректирует

**Comment by ISPLab** [comment]
стабильна и выполняться все другие условия - а то что?

**Comment by ISPLab** [comment]
Вообщем мое мнение: что autosurveying - в ui это не то что в плагине ,
поэтому предлагаю убрать auto mode из интерфейса приложения заменив его на что нибудь типа " use surveying settings"

**Comment by ISPLab** [comment]
функции безконрольного получения ни в тз ни в переписке не звучало

**Comment by kaa1965** [comment]
Назначение Автоматического режима:
1. Геодезисту сказали Измерить четыре точки.
2. Он пришел в первую точку, он запускает Автоматический режим.
3. Антенна стала стабильна и выполнились все условия съёмки) => формируется автоматически новая точка. Пользователь слышит пилим-пилим и видит что измерение выполнено в виде строки "Измерение выполнено".
4. Пользователь ничего не нажимая на UI. Идет в другую точку... Пока он идёт антенна Нестабильна. Новые измерения пока он идёт не формируются.
5. Пришёл во вторую точку. Антенна снова стала стабильна и выполнились все условия съёмки) => формируется автоматически новая точка. Пользователь слышит пилим-пилим и видит что измерение выполнено в виде строки "Измерение выполнено".
6. Дальше подобно измеряется 3я и 4я точки.
7. Измерив все четыре точки он останавливает Автоматические Измерения, при этом в Плагин нужно выдать StopSurvey()

**Comment by kaa1965** [comment]
****Вообщем мое мнение: что autosurveying - в ui это не то что в плагине ,
поэтому предлагаю убрать auto mode из интерфейса приложения заменив его на что нибудь типа " use surveying settings"****
Как раз то не так...
Всё ТЗ пронизано тем что должна быть **Ручная съёмка и Автоматическая съёмка**

**Comment by ISPLab** [comment]
а если остановится по пути к третьей?

**Comment by ISPLab** [comment]
то что вы описываете это не автоматическая cъемка, код функции у вас как отправлять данные мы обсудили 
При Ручном Измерении при каждом нажатии на кнопку Измерить вызывается StartSurvey() с Autosurveying false. Плагин выполняет одно Измерение. Обработчик события surveying_result, приняв это событие добавляет точку в Проект.
При Автоматическом Измерении при нажатии на кнопку Измерить вызывается StartSurvey() с Autosurveying true. Плагин также выполняет одно Измерение. Обработчик события surveying_result, приняв это событие добавляет точку в Проект + повторно вызывает StartSurvey() с Autosurveying true

**Comment by kaa1965** [comment]
Для Пользователя это Ручная или Автоматичкая съёмка.
А то как они реализованы, это результат переписки.
