### ISSUE TITLE
NVLirSurveingParams у NvlirPluginConfiguration не серриализуется

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#122]
В RoverConfiguration объявлен SurveingParams. SurveingParams - типа SurveyingParameters.  Плагин работает с NvlirPluginConfiguration:RoverConfiguration. В свою очередь NvlirPluginConfiguration работает с NVLirSurveingParams:SurveyingParameters. Проблема в том, что после серриализации NvlirPluginConfiguration.SurveingParams становится SurveyingParameters, а должен быть типа  NVLirSurveingParams

**Comment by ISPLab** [comment]
сериализуете его как NVLirSurveingParams?

**Comment by ISPLab** [comment]
на поле TimeSurveying в Demo показано что сереализуется десереилизуется DemoSurveyingParam без проблем

**Comment by kaa1965** [comment]
DemoSurveyingParam явно серриализуется... Тогда проблем нет.
Проблема возникает, когда Серриализуется NVLirPluginConfiguration:
var plug_config = p8Serializer.Deserialize<NVLirPluginConfiguration>((byte[])settings);
NVLirPluginConfiguration содержит SurveingParams.
И вот этот NVLirPluginConfiguration.SurveingParams не серриализуется как NVLirSurveingParams

**Comment by kaa1965** [comment]
В RoverConfiguration сделано:
    public **virtual** SurveyingParameters SurveyingParams
В NVLirPluginConfiguration сделано:
    public **override** SurveyingParameters SurveyingParams
