### ISSUE TITLE
Не сохраняются настройки введенные в экспертном меню

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#128]
1. Если вводить настройки в экспертном меню, то после выхода из программы (через меню панели управления Windows) они сбрасываются в значения по умолчанию.
2. Если вводить настройки в пользовательском интерфейсе, то они сохраняются и в экспертном меню.
3. Где хранится файл с настройками?

**Comment by ISPLab** [comment]
файл в P8DB
сохранение настроек в экспертном меню только при нажатии Enter
В дальнейшем будет также для всех элеметов UI
