### ISSUE TITLE
Parsing entering coordinate for geo project point 

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#133]
Предлагаю изменить интерфейс ввода координат для точки проекта 
для унификации ввода и удобства пользователя
Вместо ввода Lat long или чего либо другого сделать одно стринговое поле 
а AddGeoPoint  сделать парсер и выставлять lat long xzy blh neh  в классе точки программно 

double[] ParseToCoordinate(string coordinate_string);

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/81902352-ad32b200-95c8-11ea-991e-cc26592257fa.png)

**Comment by kaa1965** [comment]
Нужно сделать 3 поля ввода. Названия для полей брать так:
MeasureManager.GetGeoCoordinateTypes(geoProject.Parameters.GeoPresentationType);
Этот метод вернёт массив из трёх строк с наименованиями меток в зависимости от выбранного в проекте Типа представления координат.

**Comment by ISPLab** [comment]
давайте все таки вернемся к обсуждению предложения
В чем могут быть подводные камни?

**Comment by ISPLab** [comment]
три поля могут быть заменены одним с тремя биндингами (это мои вопросы по эргономики и стилизации)

**Comment by kaa1965** [comment]
Точку в пространстве определяют 3 координаты.
Эти 3 координаты по разному называются в зависимости от выбранного Типа представления координат (geoProject.Parameters.GeoPresentationType).
Соответственно должно быть 3 поля ввода, для каждой координаты своё поле. И каждое поле должно иметь своё название, которое зависит от выбранного Типа представления координат.

**Comment by ISPLab** [comment]
давайте говорить что у точки есть позиция которая определяется числовыми значениями
значения могут быть разные в зависимости от той системы координат в которой вводится
"Соответственно должно быть 3 поля ввода" - это не является подводным камнем

**Comment by ISPLab** [comment]
еще есть замечания ? ("Времени все меньше и меньше")

**Comment by kaa1965** [comment]
Это не замечание, это Требование: должно быть 3 поля ввода.

**Comment by ISPLab** [comment]
В ПМИ есть такое требование? 
На данный момент все требования ПМИ по вводу и отображению данных
выполняются.
Мы сейчас обсуждаем как сделать одновременно удобно для пользователя и унифицированно для продукта

**Comment by ISPLab** [comment]
если нет замечаний могу вам отправить парсер для анализа

**Comment by ISPLab** [comment]
double[] ParseToCoordinate(string coordinate_string);

where: coordinate_string : may be ds xyz dms dd ...

**Comment by ISPLab** [comment]
и наверное надо в парсер добавить еще зону которая может быть или не быть

**Comment by kaa1965** [comment]
Тип | Строка на входе | Возвращаемый double[] | Описание координат
-- | -- | -- | --
DS | 40.7600000, 73.9840000, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DD | 40.7600000N 73.9840000E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DM | 40°45.647’N, 73°59.045’E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DMS | 40°45´36.5"N, 73°59´2.4"E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
XYZ | 2698497.5703, 2955691.1168, 4949759.3818 | [0]=2698497.5703    [1]=2955691.1168   [2]=4949759.3818 | 3 координаты – расстояние от центра эллипсоида по 3-м осям.   В этом представлении всегда 3 координаты, иначе не имеет смысла
NEH | 5678616.9868959859, 681833.644440148, 203.7 | [0]=5678616.9868959859    [1]=681833.644440148   [2]=203.7 | 2 координаты на на плоскости проекции,   Высота от эллипсоида

**Comment by kaa1965** [comment]
Вот свёл в таблицу по всем типам представления, что буду ждать на входе и что верну. Для этой функции нужен строка с тремя координатами и тип представления координат. Зона и не нужна:
double[] ParseToCoordinate(string coordinate_string, GeoPresentationType presentationType);

**Comment by kaa1965** [comment]
Или тебе для DS, DD, DM, DMS радианы возвращать?

**Comment by ISPLab** [comment]
double[] for degrees is radians 
double[] for other  is meters
DS, DD, DM, DMS ==.  это как hex для int

**Comment by ISPLab** [comment]
я так понимаю по возвращаемым double[] можно определить формат введеных данных?

**Comment by ISPLab** [comment]
географическая координата - формат записии матем.,  определяющее положение точки в системе координат 
соответсвенно в таблицы в третьей колонке всегда одна координата

**Comment by kaa1965** [comment]
я так понимаю по возвращаемым double[] можно определить формат веденных данных? (в сферической или прямоугольной системе?)
Не определишь. Невозможно отличить XYZ от NEH. 
XYZ - это расстояние от центра эллипсоида. 
NEH - это расстояние от какого-то заданного меридиана.
Для BLH опять же отображать в градусах или с минутами или с секундами.

**Comment by kaa1965** [comment]
Давай ещё раз посмотрим на таблицу:

Тип | Строка на входе | Возвращаемый double[] | Описание координат
-- | -- | -- | --
DS | 40.7600000, 73.9840000, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DD | 40.7600000N 73.9840000E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DM | 40°45.647’N, 73°59.045’E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DMS | 40°45´36.5"N, 73°59´2.4"E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
XYZ | 2698497.5703, 2955691.1168, 4949759.3818 | [0]=2698497.5703    [1]=2955691.1168   [2]=4949759.3818 | 3 координаты – расстояние от центра эллипсоида по 3-м осям.   В этом представлении всегда 3 координаты, иначе не имеет смысла
NEH | 5678616.9868959859, 681833.644440148, 203.7 | [0]=5678616.9868959859    [1]=681833.644440148   [2]=203.7 | 2 координаты на на плоскости проекции,   Высота от эллипсоида

**Comment by kaa1965** [comment]
Тут я вижу 2 темы:
1. Тема разделители между целой и дробной частью (точка или запятая)... Пользователь может ставить и точку и запятую??? Или только точка??? Если будет запятая между целой и дробной частью, то эта запятая мешает при парсинге трёх координат. Ты можешь в виде разделителей между числами передавать подчёркивание вот так: 40.7600000_73.9840000_217.193 ???
Тема 2. В принципе, наверное можно и без Типа представления координат. 
Тогда правила например, такие:
- если нет знаков градуса, или апострофов (ASCII=0x27), или кавычки (ASCII=0x22) - это double
- при этом также проверяю наличие букв N(S) E(W)
- также учитывается что спереди числа может быть + или -

**Comment by ISPLab** [comment]
точка или запятая:  scientific notification standart - всегда точка. Этот выбор есть только в русском виндовсе

**Comment by ISPLab** [comment]
40.7600000_73.9840000_217.193  - нет, что ввел пользователь то и парcить если
ошибка double[] {-1,-1,-1}

**Comment by ISPLab** [comment]
плюс пользователь может ввести зону
40.7600000, 73.9840000, 217.193:12

**Comment by ISPLab** [comment]
тогда double[4] is zone
reserv:
double[5] is datum
double[6] is projection

**Comment by kaa1965** [comment]
Пользователь ввёл координаты, Функция сформировала числа.
Пользователь ввёл 40°45.647’N, 73°59.045’E, 217.193
Функция вернёт [0]=40.7600000 [1]=73.9840000 [2]=217.193 
[0]=40.7600000 [1]=73.9840000 - **Это градусы**
Что ты с ними дальше делаешь????
Предположим, вызываешь ConvertGeoCoordinates.
В неё ты должен передать уже радианы. 
То есть вызывал Парсер, получил от парсера градусы [0]=40.7600000 [1]=73.9840000 [2]=217.193, перевёл в радианы, вызвал ConvertGeoCoordinates с радианами.
Если так, то мне ни зоны, ни датумы, ни проекции, ни Тип представления координат не нужны.
Если у тебя другая логика, то какая?

**Comment by ISPLab** [comment]
мы работаем только с радианами, соответственно для ConvertGeoCoordinates Вы сами себе положите то что вам нужно

**Comment by ISPLab** [comment]
тогда double[4] is zone
reserv:
double[5] is datum
double[6] is projection
double[7] is format (DS, XYZ ,,,,)
номер- из енама

**Comment by ISPLab** [comment]
double[] Coordinate = new ....
  double[1] is latitude or x 
  double[2] is longitude or y
  double[3] is height (meters)
  double[4] id datum
  double [5] is projection
  double[6] is format 
  double[7] is zone

**Comment by kaa1965** [comment]
Что вводит пользователь?

**Comment by ISPLab** [comment]
coordinate_notation examples : 34.7600000, 73.9840000, 217.193:12
                                                      34.7600000, 73.9840000, 217.193
                                                      2698497.5703, 2955691.1168, 4949759.3818
double[] ParseToP8Coordinate(this string coordinate_notation, string datum, string projection)
{
return p8coordinate_notation
/*
p8coordinate_notation:
  double[] P8Coordinate = new ...
  double[0] is latitude or x 
  double[1] is longitude or y
  double[2] is height (meters)
  double[3] id datum
  double [4] is projection
  double[5] is format 
  double[6] is zone 
*/
}

**Comment by kaa1965** [comment]
Пришёл ко мне string datum="project", что я дальше с ним должен делать?

**Comment by ISPLab** [comment]
вы цифру из енама пишете

**Comment by kaa1965** [comment]
double[5] is format - это что такое?

**Comment by ISPLab** [comment]
ds, dms, xyz...

**Comment by kaa1965** [comment]
А как я его сформирую?

**Comment by ISPLab** [comment]
цифрой из енама

**Comment by kaa1965** [comment]
По каким правилам это делать?

**Comment by ISPLab** [comment]
вы же писали что если есть градус то...

**Comment by kaa1965** [comment]
А если градуса нет, то это может быть DS или NEH или XYZ

**Comment by ISPLab** [comment]
цифры в DS до 180
+ информация о datum и проекции есть

**Comment by ISPLab** [comment]
примеры из таблицы всяка распарсятся

**Comment by kaa1965** [comment]
Пользователь находится в 50 метрах от Центрального меридиана или от Центра Полюса Хотина (как в варианте Заказчика). Тогда Координаты NEH будут следующие:
NEH = 50, 50, 200 (что означает что он 50 метров севернее и 50 западнее некоторого Центра Пользовательской Системы Координат).
DS = 50, 50, 200 - это тоже может быть: 50 градусов Севверной Широты, 50 градусов от Гринвича.
Высота и там и там по 200 метров от эллипсоида

**Comment by kaa1965** [comment]
То есть невозможно определить NEH или DS....

**Comment by kaa1965** [comment]
Добавил рассматриваемый вариант в Таблицу возможных значений координат:
Тип | Строка на входе | Возвращаемый double[] | Описание координат
-- | -- | -- | --
DS | 40.7600000, 73.9840000, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DD | 40.7600000N 73.9840000E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DM | 40°45.647’N, 73°59.045’E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
DMS | 40°45´36.5"N, 73°59´2.4"E, 217.193 | [0]=40.7600000 [1]=73.9840000   [2]=217.193 | 2 координаты на эллипсоиде,   Высота от эллипсоида
XYZ | 2698497.5703, 2955691.1168, 4949759.3818 | [0]=2698497.5703    [1]=2955691.1168   [2]=4949759.3818 | 3 координаты – расстояние от центра эллипсоида по 3-м осям.   В этом представлении всегда 3 координаты, иначе не имеет смысла
NEH | 5678616.9868959859, 681833.644440148, 203.7 | [0]=5678616.9868959859    [1]=681833.644440148   [2]=203.7 | 2 координаты на на плоскости проекции,   Высота от эллипсоида
NEH | 50.9, 50.6, 203.7 | [0]=50.9    [1]=50.6   [2]=203.7 | 2 координаты на на плоскости проекции,   Высота от эллипсоида

**Comment by ISPLab** [comment]
То есть невозможно определить NEH или DS....
случае невозможности возвращайте ошибку double[]{-1,-,1,-1}
* DS = 50, 50,  
DS = 50, 50, 200  не возможно. - это значит ровер находится на 200 метрах над землей

**Comment by ISPLab** [comment]
DS | 40.7600000, 73.9840000, 217.193 | [0]=40.7600000 [1]=73.9840000 [2]=217.193 | 2 координаты на эллипсоиде, Высота от эллипсоида
-- | -- | -- | --
где вы взяли что это высота на элипсойдом?

**Comment by ISPLab** [comment]
откройте какое нибудь приложение на телефоне и посмотрите на какой высоте вы находитесь

**Comment by ISPLab** [comment]
если интересно могу еще скинуть данные с бортовых компьютеров на самолетах

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/133#issuecomment-633084762
Значит твоя любимая точка 51.22986, 47.60443 попадает в число ошибок ???

**Comment by ISPLab** [comment]
моя любимая точка находится на уровне земли 0 
с ней все хорошо)

**Comment by kaa1965** [comment]
Ко мне с Ровера приходит высота = 200метров. Это Высота над элипсоидом Земли WGS84. Геодезист будет мерять Высоту над элипсоидом Земли. Он будет вводить координаты над элипсоидом Земли.

**Comment by ISPLab** [comment]
пусть меряет - мы говорим о вводе точки

**Comment by ISPLab** [comment]
если совсем по жесткому можно сделать ввод для blh:
blh: 234,234,34.

**Comment by ISPLab** [comment]
я просмотрел все калькуляторы которые мы использовали нигде высота в DS - вообще не вводится
соответсвенно: p8coordinate notification  для DS = это высота над землей будет

**Comment by ISPLab** [comment]
Еще в парсере учитывайте - что высота может не вводится как во всех geocalculatorах

**Comment by kaa1965** [comment]
1. Задаваться высота должна во всех Типах представления координат. Если это ты не хочешь этого делать - пиши Булавскому и решай с ним.
2. Я с Булавским разговаривал только что по телефону, он категорически против такого подхода, чтобы Программа определяла в каком типе представления вводятся координаты. И Булавский и Кузьмицкий говорят, что Пользователь прежде чем ввести координаты должен определить Тип (DS, NEH...) На лету программа это не сможет сделать.

**Comment by ISPLab** [comment]
вы отказываетесь парсер делать?

**Comment by kaa1965** [comment]
Парсер без указания типа представления координат на входе невозможно реализовать. На вход парсера этот параметр должен поступать. Напиши в спецификации функции парсера, как он будет передаваться

**Comment by ISPLab** [comment]
если совсем по жесткому можно сделать ввод для NEH:
NEH: 234,234,34.......

**Comment by ISPLab** [comment]
Парсер без указания типа представления координат на входе невозможно реализовать
Спорим ?

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/133#issuecomment-633093284
По моему это ты не выполняешь Требования ТЗ, мои, Булавского и Кузьмицкого. Все требуют, чтобы Пользователь сначала задавал Тип представления координат, а потом их вводил

**Comment by ISPLab** [comment]
#133 (comment)
По моему это ты не выполняешь Требования ТЗ, мои, Булавского и Кузьмицкого. Все требуют, чтобы Пользователь сначала задавал Тип представления координат, а потом их вводил 
пользователь когда вводит задает тип представления,
это вы не хотите делать дружелебно)

**Comment by kaa1965** [comment]
пользователь когда вводит задает тип представления,
это вы не хотите делать дружелебно)
Как в парсер поступит информация о Типе представления, прежде чем парсер начнет работать?

**Comment by kaa1965** [comment]
Булавский подтвердил, что значения меньше 90 могут быть в HEH координатах. Так как всё зависит от того как задана Пользовательская Система координат. При вводе вводе координат в любом типе представления должно быть 3 координаты

**Comment by kaa1965** [comment]
Парсер реализован
Тесты отправил по почте
Парсер либо автоматически распознаёт введённый формат, либо работает по переданному формату.

**Comment by ISPLab** [comment]
CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.NEH, (double)DatumIdEx.PROJECT, (double)GeoProjectionIdEx.UTM, -1);
для NEH может быть не Project?

**Comment by ISPLab** [comment]
string coordinate = "34.7600000,,,";//Пустая строка между запятыми - это нулевые координаты
Это так нули собираемся вводить?

**Comment by ISPLab** [comment]
не нашел парс на 34.7600000, 73.9840000     DS

**Comment by kaa1965** [comment]
CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.NEH, (double)DatumIdEx.PROJECT, (double)GeoProjectionIdEx.UTM, -1);
для NEH может быть не DatumIdEx.PROJECT?
Может быть любой для всех типов представления координат

**Comment by kaa1965** [comment]
string coordinate = "34.7600000,,,";//Пустая строка между запятыми - это нулевые координаты
Это так нули собираемся вводить?
Ну, такая возможность есть, хотел сначала ошибку выдавать, потом решил оставить

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/133#issuecomment-633250758
public void ParserSeparatorTest_9()
        {
            //Два дабла в предалах -90...90 и -180...180 - вернутся DS и радианы и высота = 0
            string datum = DatumIdEx.PROJECT.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();            
            string coordinate = "51.22986, 47.60443";//DS - OK
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            CheckCoordinates(p8CoordinateContext, P8.Geo.units.deg2rad(51.22986), P8.Geo.units.deg2rad(47.60443), 0);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DS, (double)DatumIdEx.PROJECT, (double)GeoProjectionIdEx.UTM, -1);
        }

**Comment by ISPLab** [comment]
2698497.5703, 2955691.1168, 4949759.3818 | [0]=2698497.5703 [1]=2955691.1168 [2]=4949759.3818 | 3 координаты – расстояние от центра эллипсоида по 3-м осям. В этом представлении всегда 3 координаты, иначе не имеет смысла
-- | -- | --
NEH | 5678616.9868959859, 681833.644440148, 203.7 | [0]=5678616.9868959859 [1]=681833.644440148 [2]=203.7 | 2 координаты на на плоскости проекции, Высота от эллипсоида
NEH | 50.9, 50.6, 203.7 | [0]=50.9 [1]=50.6 [2]=203.7 | 2 координаты на на плоскости проекции, Высота от эллипсоида


в таблице не увидел разницы  в xyz. - x же тот же самый север что и в NEH?

**Comment by ISPLab** [comment]
Привидете в соответвие P8 Coordinate notation and p8 entering format

https://docs.google.com/document/d/1EBxs96jNLXTjz832dEvYOJYBz3vQeJf4CdsVIXOM5AA/edit#heading=h.db5asgnk940x

**Comment by kaa1965** [comment]
Теперь авто-парсер для NEH ожидает то, что на конце будет установлен NилиS, EилиW, но знака градуса при этом не будет.
Полные тесты выслал по почте.

Ниже тесты для таблицы по документации NVSPoint (в полных тестах они также есть)

[Test]
        public void ParserSeparatorTable_DS_1()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "40.7600000, 73.9840000"; //38 - номер зоны            
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            double lat = P8.Geo.units.deg2rad(40.76);
            double lon = P8.Geo.units.deg2rad(73.984);
            CheckCoordinates(p8CoordinateContext, lat, lon, 0);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DS, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, -1);
        }
        [Test]
        public void ParserSeparatorTable_DS_2()
        {         
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "40.7600000, 73.9840000:38";
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            double lat = P8.Geo.units.deg2rad(40.76);
            double lon = P8.Geo.units.deg2rad(73.984);
            CheckCoordinates(p8CoordinateContext, lat, lon, 0);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DS, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, 38);
        }
        [Test]
        public void ParserSeparatorTable_DD_1()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "40.76°, 73.984°,217.193"; //38 - номер зоны            
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            double lat = P8.Geo.units.deg2rad(40.76);
            double lon = P8.Geo.units.deg2rad(73.984);
            CheckCoordinates(p8CoordinateContext, lat, lon, 217.193);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DD, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, -1);
        }
        [Test]
        public void ParserSeparatorTable_DD_2()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "40.76°, 73.984°,217.193:38"; //38 - номер зоны            
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            double lat = P8.Geo.units.deg2rad(40.76);
            double lon = P8.Geo.units.deg2rad(73.984);
            CheckCoordinates(p8CoordinateContext, lat, lon, 217.193);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DD, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, 38);
        }
        [Test]
        public void ParserSeparatorTable_DMS_1()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "40°45'36.5''N, 73°59'2.4''E, 217.193"; //38 - номер зоны            
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            double lat = P8.Geo.units.deg2rad(40.0 + 45.0 / 60.0 + 36.5 / 3600);
            double lon = P8.Geo.units.deg2rad(73.0 + 59.0 / 60.0 + 2.4 / 3600);
            CheckCoordinates(p8CoordinateContext, lat, lon, 217.193);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DMS, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, -1);
        }
        [Test]
        public void ParserSeparatorTable_DMS_2()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "40°45'36.5''N, 73°59'2.4''E, 217.193:38"; //38 - номер зоны            
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            double lat = P8.Geo.units.deg2rad(40.0 + 45.0 / 60.0 + 36.5 / 3600);
            double lon = P8.Geo.units.deg2rad(73.0 + 59.0 / 60.0 + 2.4 / 3600);
            CheckCoordinates(p8CoordinateContext, lat, lon, 217.193);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.DMS, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, 38);
        }
        [Test]
        public void ParserSeparatorTable_XYZ()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "2698497.5703, 2955691.1168, 4949759.3818"; //38 - номер зоны            
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);
                        
            CheckCoordinates(p8CoordinateContext, 2698497.5703, 2955691.1168, 4949759.3818);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.XYZ, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, -1);
        }
        [Test]
        public void ParserSeparatorTable_NEH()
        {            
            string datum = DatumIdEx.WGS84.ToString();
            string projection = GeoProjectionIdEx.UTM.ToString();
            string coordinate = "5678616.9868959859N, 681833.6444E, 203.7";
            double[] p8CoordinateContext = GeoCoordinateParser.ParseToP8Coordinate(coordinate, datum, projection);

            CheckCoordinates(p8CoordinateContext, 5678616.9868959859, 681833.6444, 203.7);
            CheckResultTest(p8CoordinateContext, (double)GeoPresentationType.NEH, (double)DatumIdEx.WGS84, (double)GeoProjectionIdEx.UTM, -1);
        }

**Comment by ISPLab** [comment]
Ниже тесты для таблицы по документации NVSPoint (в полных тестах они также есть)
сделано не по документации
enumы не соответсвуют, форматы данных тоже
