### ISSUE TITLE
Обработка события error

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#134]
Нужно определиться с той ситуацией, которая возникает во время работы NVSPoint.
Есть событие ActionName=error
Оно генерится с DataType=base_station (или rover)
Во время работы возникают две ситуации:
**Ситуация 1:** Плагин устанавливает Связь с Сервером или Ровером, а потом связь рвётся. Плагин автоматически восстанавливает соединение с Сервером или Ровером. Через какое-то время опять связь разрывается. Плагин снова автоматически восстанавливает соединение. При каждом разрыве связи Плагин генерит Событие на шину ActionName=error. UI затемняет экран, показывает Диалог и ждёт пока Пользователь не нажмёт кнопку Accept.
 
![image](https://user-images.githubusercontent.com/50620286/81920872-7cf80d00-95e2-11ea-8852-4db8cf09b052.png)

В этой ситуации достаточно подсветить соответствующий значок для БС или Ровера:
 
![image](https://user-images.githubusercontent.com/50620286/81920920-8a14fc00-95e2-11ea-90ae-65268f02c218.png)

По идее также нужно отобразить текст ошибки (**НО БЕЗ Диалога** и без подтверждения Пользователем на кнопку Accept).
Если сейчас Проблема с отображением Текста ошибки без Диалога, тогда пока только подсветить значок без Диалога.
**Ситуация 2:** Пользователь неверно определяет Настройки, или в ходе Подключения к Серверу не проходит Процедура Аутентификации (неверный логин-пароль). В этом случае нужна реакция такая, как сейчас, то есть с Диалогом Пользователю и с кнопкой Accept.
**Предложение:**
В событие ActionName=error добавить использование Parametr, который сейчас не используется.
Например:
Если Плагин выставляет Parametr=”0” то UI подсвечивает соответствующий значок для БС или Ровера, Показывает Диалог Пользователю.
Если Плагин выставляет Parametr=”1” то UI подсвечивает соответствующий значок для БС или Ровера, Показывает Текст ошибки БЕЗ Диалога Пользователю (без затемнения экрана, без кнопки Accept и без ожидания нажатия на неё).

**Comment by ISPLab** [comment]
fixed  
 if (String.IsNullOrEmpty(e.Description)). //don't show user message

**Comment by kaa1965** [comment]
Не понял...
Что в итоге будет?

**Comment by kaa1965** [comment]
И как должен выставлять События Плагин в этих двух рассмотренных Ситуациях?

**Comment by ISPLab** [comment]
если дескриптиона нет - паказываться сообщение не будет
если есть будет
восклицательный знак будет выставляться на индикатор в любом случае

**Comment by kaa1965** [comment]
А как Пользователь узнает причину ошибки? Где он посмотрит текстовку этой ошибки?

**Comment by ISPLab** [comment]
в параметрах вы оказываете номер ошибки в ресурсы кладете описание 
в логер пишите подробно

**Comment by kaa1965** [comment]
1. Что такое журнал событий? Это в чистом виде лог-файл? Или что-то другое? Что попадает в журнал событий из событий, который генерит плагин на шине?
2. номер ошибки в параметрах - это имеется ввиду string - Ключ в Dictionary Ресурсов?

**Comment by ISPLab** [comment]
1. как я показывал вам на маршрутизаторе в офисе
2. да, любой стринг. Для удобства и для документации лучше сделать чтобы выглядело как число c буквами CE123   (это тоже уже обсуждали)

**Comment by kaa1965** [comment]
В каком классе этот Dictionary Ресурсов? Тогда сейчас буду его наполнять
