### ISSUE TITLE
Текстовки ошибок от Плагина

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#137]
В плагине сейчас те ошибки, которые возникают при работе на каналах связи выведены через события на шину без Descriptiona с целью отображения ошибки на значке Ровера или БС.
Но фактически возникают ситуации когда Связь может временно на какое-то время пропасть, плагин будет её восстанавливать при запущенной RTK, и эти ошибки установления связи валятся и валятся. Пользователь по идее должен видеть ошибку на значке и ожидать восстановления связи, то есть в этой ситуации он знает причину и ему показывать каждый раз Диалог с подтверждением на кнопку Accept не нужно.
С другой стороны от Плагина есть и критичные ошибки (например, ошибка аутентификации), которые нужно вывести через Диалог Пользователю и отобразить на значке.
Нужно какое-то решение, чтобы плагин мог передавать ошибку с Диалогом и без Диалога. Но если и без Диалога, то текст ошибки должен попасть в журнал.

**Comment by ISPLab** [comment]
Description  empty - нет сообщения
Parametr - поподает в журнал
Примеры использования  сообщений с парметрами находится в Demopluginimplementation 
На значке появляется восклицательный знак текст в соответсвии с документацией предусмотрен только если нет ошибки

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82071604-042aab00-96df-11ea-9917-5ab329889f81.png)
для ровер и для базовой станции показать можно

**Comment by kaa1965** [comment]
**Description empty - нет сообщения
Parametr - поподает в журнал
Примеры использования сообщений с парметрами находится в Demopluginimplementation**

Что-то как то не вяжется всё это вцелом:
Вот код в public class RoverManager:
if (String.IsNullOrEmpty(e.Description))
                                    return;
                                var message = e.Description.GetStrFromresource();
                               
                                var parameter = e.Parametr;
                                if(!String.IsNullOrEmpty(parameter))
                                {
                                    message = String.Format(message, parameter);
                                }

То есть e.Parametr - это параметр для получения полной строки текста ошибки.
Причём e.Parametr обрабатывается только если e.Description непустой.
Если только "Parametr - попадает в журнал" - то в журнал попадёт часть текста ошибки, а нужно чтобы в журнал сохранился весь текст ошибки.

**Есть предложение:**
- я пока в плагине разделил все ошибки на две части (с Диалогом пользователю -e.Description непустой, без диалога (только для значка) - e.Description пустой)
Думаю пока этого хватит.
