### ISSUE TITLE
Размер окна программы не "на весь экран"

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#138]
Окно программы отображается не "на весь экран" - в верхней части экрана отображается часть рабочего стола Windows
![Безымянный1](https://user-images.githubusercontent.com/59056870/82069709-6504b400-96dc-11ea-9c2b-1ebe36831b94.png)

**Comment by ISPLab** [comment]
Панель управления Windows #129
 Open	tipin1 opened this issue 4 days ago · 1 comment
Comments
@tipin1
 
Collaborator
tipin1 commented 4 days ago
Если панель управления Windows закреплена в правой части экрана, то при открытии программы :

в нижней части экрана отображается рабочий стол (программа открывается не во весь экран);
часть интерфейса программы находится за панелью управления, расположенной справа.
@tipin1 tipin1 assigned ISPLab, kaa1965 and tipin1 4 days ago
@ISPLab
 
Owner
ISPLab commented 3 days ago
1.виндовс при расчете высоты экрана всегда выдает информацию что всегда есть нижняя панель и верхняя строка на окне программы
2. при изменении разрешений экрана и масштабирования невозможно получить правильные размеры экрана что бы рассчитать размеры элементов под размер окна
Проблема требует проработки
