### ISSUE TITLE
Нет клавиатуры

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#139]
Нет возможности ввести настройки (в т.ч. в экспертном меню), т.к. отсутствует клавиатура.
![Безымянный1](https://user-images.githubusercontent.com/59056870/82070977-1eb05480-96de-11ea-81c5-4f82b15d659c.png)
![Безымянный2](https://user-images.githubusercontent.com/59056870/82071029-312a8e00-96de-11ea-9d74-7d56f51c0ce8.png)

**Comment by ISPLab** [comment]
при какой ситуации это случилось?

**Comment by tipin1** [comment]
С момента запуска новой версии программы.
Переоткрытие программы не исправляет ситуацию.
Подключение внешней клавиатуры дает возможность ввести буквы, но не цифры. Кнопки Esc и Enter также не работают в программе с внешней клавиатуры.

**Comment by ISPLab** [comment]
Попробуйте папку  p8db удалить

**Comment by ISPLab** [comment]
у меня работает клава как раньше

![image](https://user-images.githubusercontent.com/8803512/82074636-bf554300-96e3-11ea-8b44-d7381ede715b.png)

**Comment by ISPLab** [comment]
стоп, полноэкранный режим  на десктопе не делал 
если нужно добавь предложение в NVSPoint (buildversion)

**Comment by tipin1** [comment]
Что означает "полноэкранный режим на десктопе не делал"?
В настройках windows ничего не менялось.
Вот скрин с прошлой версией программы где клавиатура есть
![Безымянный3](https://user-images.githubusercontent.com/59056870/82081927-c8e4a800-96ef-11ea-91ac-9cbe248e69f0.png)
:

**Comment by ISPLab** [comment]
разрешение экрана покажите

**Comment by tipin1** [comment]
1. Разрешение экрана
![Uploading Безымянный4.png…]()
2. Ссылка на видео с отсутствующей клавиатурой
https://cloud.mail.ru/public/McS2/xVhhWDzDK

**Comment by ISPLab** [comment]
попробуйте поставить 800 на 600 со 100 процентами

**Comment by tipin1** [comment]
На разрешении экрана 800х600 клавиатура есть. Но что будем делать когда Заказчик попросит выставить максимальное разрешение планшета?

**Comment by ISPLab** [comment]
в работе
