### ISSUE TITLE
bad commit for error desctiption

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#140]
Ранее плагин формировал все события error с description != string.Empty.
Сделано разделение, теперь плагин формирует error:
- с description = string.Empty (с целью отображения на значке)
- с description != string.Empty (с целью их показа Пользователю через Диалог на UI)

**Comment by ISPLab** [comment]
в комите есть фалы которые в перечисленные вами измененения не долны входить 
/NVSProjects/UiNVSPoint/UINVSPoint.projitems
p8xamarin 

на данный момент есть возмоюжность отключить пользовательские сообщения об ошибках

**Comment by ISPLab** [comment]
в тестах самой проверки на если есть description или  нет - нет:
 
            Assert.IsTrue(_countErrorsRoverWithDescription > 0);
            Assert.IsTrue(_countErrorsRoverWithoutDescription > 0);
            Assert.IsTrue(_countErrorsServerWithDescription > 0);
            Assert.IsTrue(_countErrorsServerWithoutDescription > 0);

**Comment by ISPLab** [comment]
фото после мержа с удаленной веткой
по выполненным тестам так нет

**Comment by ISPLab** [comment]
в pluginhelper/stringresourses  не добвалены параметры которые вы высылали по ошибкам 
тестов соответсвенно на них тоже нет

**Comment by kaa1965** [comment]
в комите есть фалы которые в перечисленные вами измененения не долны входить
/NVSProjects/UiNVSPoint/UINVSPoint.projitems
p8xamarin
Это приехало во время Pull

**Comment by kaa1965** [comment]
Тесты

![IMG-20200513-WA0105](https://user-images.githubusercontent.com/50620286/82112694-f7966900-9757-11ea-985a-a6762c586e54.jpeg)

**Comment by kaa1965** [comment]
![ErrorTest](https://user-images.githubusercontent.com/50620286/82112725-5eb41d80-9758-11ea-8d85-08fdde483bb1.png)

**Comment by kaa1965** [comment]
в тестах самой проверки на если есть description или нет - нет:
Как же нет?
Вот код:

case NVlirEventBusHelper.NVlirTypeRoverName:
                            
                            switch (e.ActionName)
                            {
                                case "error":
                                    if (String.IsNullOrEmpty(e.Description))
                                        _countErrorsRoverWithoutDescription++;
                                    else
                                        _countErrorsRoverWithDescription++;
                                    break;
                            }
                            break;
                        case NVlirEventBusHelper.NVlirTypeServerName:

                            switch (e.ActionName)
                            {
                                case "error":
                                    if (String.IsNullOrEmpty(e.Description))
                                        _countErrorsServerWithoutDescription++;
                                    else
                                        _countErrorsServerWithDescription++;
                                    break;
                            }
                            break;

**Comment by ISPLab** [comment]
eсть ассерт на кооличесво по функционалу (те функции которы вы используете не проверятся)
        Assert.IsTrue(_countErrorsRoverWithDescription > 0);
        Assert.IsTrue(_countErrorsRoverWithoutDescription > 0);
        Assert.IsTrue(_countErrorsServerWithDescription > 0);
        Assert.IsTrue(_countErrorsServerWithoutDescription > 0);

**Comment by ISPLab** [comment]
это не обходимо для того что если в UI не будет предусмотрено ваши функции работать не будут

**Comment by ISPLab** [comment]
в комите есть фалы которые в перечисленные вами измененения не долны входить
/NVSProjects/UiNVSPoint/UINVSPoint.projitems
p8xamarin
Это приехало во время Pull


на данный момент они изменены. Я писал что обновление xamarin до 4.8  в вашам проекте не проводилось - если я комит применю мы потерям другие комиты

**Comment by kaa1965** [comment]
Нужна помошь: как обновить xamarin до 4.8? Что-то еще нужно сделать в Проекте? 

![P8testProject](https://user-images.githubusercontent.com/50620286/82114953-83b08c80-9768-11ea-8ef6-fca6b4617b94.png)

**Comment by ISPLab** [comment]
для плагина и для тестов  и это не нужно

**Comment by ISPLab** [comment]
скиньте фото репозитория с gitextension и фото о выполнении тестов, начнем слияние делать
