### ISSUE TITLE
Не открывается панель индикации

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#141]
Панель индикации (верхняя) программы не открывается. При этом левая панель программы работает. Ссылка на видео:
https://cloud.mail.ru/public/esrB/5iTkQC9Hy
Порядок воспроизведения:
1. Удалить папку P8DB
2. Запустить программу -> Панель индикации не работает

**Comment by ISPLab** [comment]
на каком разрешении?

**Comment by ISPLab** [comment]
и на видео покажите как пальцем это делаете

**Comment by ISPLab** [comment]
либо можно пока я ее всегда показывать

**Comment by tipin1** [comment]
Разрешение 800х600 с другими сейчас смысла работать нет.
Видео по ссылке https://cloud.mail.ru/public/23Fm/3uMYX62o9

**Comment by ISPLab** [comment]
fixed
