### ISSUE TITLE
Уведомление Пользователя с Диалогом от плагина

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#142]
После получения списка Точек монтирования БС требуется информировать пользователя о факте получения данного списка или об Ошибке получения списка. В случае ошибки нужна формализация для формирования текста с параметрами (в параметрах какая именно ошибка произошла).
Нужно событие по шине для решения  данного функционала.
На Диалоге одна кнопка "Закрыть"

**Comment by ISPLab** [comment]
на данный момент функция проверена, если ли нет то почему?

**Comment by ISPLab** [comment]
Текст сообщения будет выводится по таким же правилам как и в Error message

**Comment by ISPLab** [comment]
В demopluginimplementation есть пример: 
  EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.configuration_changed, "", "availabe new values to configurate"));

**Comment by kaa1965** [comment]
Список БС после приема сохранеятся в настройках Плагина
configuration_changed выставляется на шину
В настройках в Экспертном виде видны записи принятого Списка БС
Но сейчас Пользователю непонятно выполнена задача или нет, так как нет Уведомления об этом.

**Comment by ISPLab** [comment]
Пользователь просил ее выполнять чтобы уведомляться?

**Comment by kaa1965** [comment]
После выполнения задачи получения Списка ему об этом нужно сказать, чтобы он понял, что задача выполнена и список получен.

**Comment by ISPLab** [comment]
" Списка ему об этом нужно сказать " пользователь просил ему об этом говорить?
