### ISSUE TITLE
invalid lat long (DS (blh)) format

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#144]
![image](https://user-images.githubusercontent.com/8803512/82138642-a1462a80-982a-11ea-954d-0f9cee2b9e3b.png)

**Comment by ISPLab** [comment]
1. для совместимости и однозначности понимания страндартого формата для всех картографических программ необходимо исправить отображение
на
![image](https://user-images.githubusercontent.com/8803512/82138700-174a9180-982b-11ea-89a9-56db54dc010f.png)
или
![image](https://user-images.githubusercontent.com/8803512/82138735-5f69b400-982b-11ea-8b39-bb49f8c79320.png)

**Comment by ISPLab** [comment]
кроме того: по умолчанию отображается именно это формат:
![image](https://user-images.githubusercontent.com/8803512/82138759-9344d980-982b-11ea-8e1b-d1a64d0658a2.png)
Поэтому представляется разумным при клике на позицию выводит DDS ( с градусами и и направлением W and E)

**Comment by kaa1965** [comment]
Ты хочешь, чтобы функция 
internal string GetAppereanceCoordinate(double[] position)
возвращала не три координаты, а две?
По поводу точности (количество знаков после запятой) - сейчас все Типы представления рассчитаны исходя из точности до 1 мм

**Comment by ISPLab** [comment]
нули зачем?
Altitude переводится как высота
ее значение представлено
для отличных от DS формата возвращайте три координаты

**Comment by ISPLab** [comment]
на DS формат - возращайте DDS

**Comment by kaa1965** [comment]
1. Обрезал нули на концах координат
2. Для Типов представления координат BLH_Deg,BLH_Min,BLH_Sec,NEH_Meter
функция GetAppereanceCoordinate возвращает две координаты
Для Типа представления координат XYZ_Meter
функция GetAppereanceCoordinate возвращает три координаты
3. Все функции проекта теперь проверяют свойства Parameters, ProjectDatum,ProjectProjection. Если они не определены в Dictionary, то выставляются WGS84, ГауссКрюгер, BLH_Deg

**Comment by ISPLab** [comment]
пришлите тесты

**Comment by kaa1965** [comment]
GeoProject geoProject = new GeoProject();

            double[] p1 = new double[] { 55.835801, 37.972990 };            
            p1 = ToRadians(p1);
            p1[2] = 1.73;
                        
            string str = geoProject.GetAppereanceCoordinate(p1);
            
            Assert.IsTrue(str == "55,835801N 37,97299E");

**Comment by ISPLab** [comment]
нет там  N и W

**Comment by ISPLab** [comment]
Знаете почему разработчики картографических систем это не пишут ?
