### ISSUE TITLE
fatal bug  from GetAppereanceCoordinate

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#145]
При возвращении string из getappereance 
если задан проект по умолчанию  

Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.InvalidCastException: Specified cast is not valid.
  at RoverPluginHelper.GeoProject.get_ProjectDatum () [0x00001] in /Volumes/Toshiba/Projects/P8Projects/P8Project2019/NVSProjects/RoverPluginHelper/GeoProjects/GeoProject.cs:201

**Comment by kaa1965** [comment]
Эта ошибка возникает из-за того что в GeoProject не определён ProjectDatum, судя по всему он равен null.
При использовании данной функции у GeoProjecta должно быть определено следующее:
ProjectDatum.Datum, ProjectProjection.Projection, Parameters.GeoPresentationType

Я поставлю в функции проверки на то, чтобы проверять наличие этих параметров.
Но если их нет, то функция всё равно бросит Exception… Или нужно тогда определять, что она должна вернуть в этом случае...

**Comment by ISPLab** [comment]
Datum по умолчание просто выстовите

**Comment by ISPLab** [comment]
WGS84

**Comment by ISPLab** [comment]
Exception на биндинги к UI НЕЛЬЗЯ выставлять

**Comment by kaa1965** [comment]
Проблема заключалась в том, что свойства стали элементами Dictionary.
В Конструкторе была и есть инициализация всех свойств в значения по умолчанию.
Но по видимому после вызова конструктора GeoProjecta через загрузку через Dictionary эти свойства сбрасываются в null.
Теперь во всех функциях класса выполняется проверка и инициализация свойств Parameters, ProjectDatum, ProjectProjection в значения по умолчанию BLH_Deg, WGS84, ГауссКрюгер

**Comment by ISPLab** [comment]
имя commit с испарвлением добавьте в собщение

**Comment by ISPLab** [comment]
и я подумал может на клик возвращать на первый клик коодинаты на плоскости(проектции в geoproject) на второй на шаре? Как пример с проектом по умолчанию WGS84: первый клик DS(Blh) второй - xyz ?

**Comment by kaa1965** [comment]
О каком клике ты говоришь? на какой странице? На каком отображаемом поле?

**Comment by ISPLab** [comment]
картинку по invalid lat long скидывал и на видео при разговоре по вотаппу показывал
