### ISSUE TITLE
Target Points

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#147]
Практически проверить добавление точек не удалось ввиду того, что Приложение «вылетает» при работе на данной странице. А именно:
Ситуация 1:
-нажать кнопку активность;
-перейти на страницу Surveying Plan;
-нажать кнопку «+» в поле Target Point;
-ввести значения в поля «Name», «Description», «Latitude», «Longitude»
-нажать кнопку «Accept»;
-на странице Surveying Plan отобразится новая Target Point;
**_-если листать страницу вверх-вниз, то новая Target Point остается в одном и том же месте экрана, хотя остальные элементы листаются;_**
**_-при кликах на созданный Target Point программа зависает;_**
-в диалоговом окне Windows нажать кнопку «Закрыть программу»;
-запустить программу;
**_-нажать кнопку активность -> программа закрывается._**
Видео по ссылке https://cloud.mail.ru/public/3z7p/2SxugpgVY
Ситуация 2:
-на странице Surveying Plan ввести любое значение в поле Name;
-закрыть программу (левая панель-> exit);
-запустить программу;
**_-нажать кнопку активность -> программа закрывается;_**

**Comment by ISPLab** [comment]
invalid y position binding on new ui element #131

**Comment by tipin1** [comment]
> invalid y position binding on new ui element

Помимо привязки позиции Target Point, описаны еще вылеты из приложения. Почему закрыт данный Issue? Если дубль, то логичнее закрыть #131 , в котором описана одна проблема!

**Comment by ISPLab** [comment]
вылет из программы был связан с фатальным багом : 
fatal bug from GetAppereanceCoordinate bug wontfix
#145 by ISPLab was closed 2 hours ago

**Comment by ISPLab** [comment]
проблему лучше дополнить а не создавать новую
