### ISSUE TITLE
Автостарт (автовключение кнопки "Активность")

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#148]
После перезапуска программы с включенным автостартом:
- Значки для Ровера и БС, то в выключенном состоянии оба, то во включенном состоянии оба, то один включен, а другой выключен
- хотя по логам видно, что включение работы с Ровером и БС произошло и информация от Ровера приходит, а также отображаются координаты и др. на странице Съёмка

**Comment by ISPLab** [comment]
в ветке по NVSPoint 23100 писал что есть проблемы с установлением начальных значений после autostart 
буду смотреть

**Comment by ISPLab** [comment]
fixed
