### ISSUE TITLE
Rover view page

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#149]
![страница измерения](https://user-images.githubusercontent.com/59056870/82159730-1a7c6680-9899-11ea-9081-18cee89bb622.png)

1)	Значение в поле «Heading» отображается в радианах. Необходимо отображать в градусах.
2)	Значение поля «Heading» перекрывает часть названия;
3)	Часть значения поля «Heading» не влезает в поле по ширине;
4)	Наименование поля «Acurren» неверно, правильно «Аccuracy»;
5)	Часть значения поля «Acurren» не влезает в поле по высоте;
6)	В поле «Acurren» сейчас отображается 3 значения (точность по широте, долготе и высоте), нужно по ТЗ (отображать два значения: точность в плане (вычисляется из точностей по широте и долготе) и точность по высоте;
7)	Не отображается значение поля «Rover mode»;
8)	Не отображается значение поля «Rover time»;
9)	Название поля «Rover time» не влезает по высоте;
10)	Наименование поля «Sattelities» неверно, правильно «Satellites»
11)	Значение поля «Sattelities» перекрывает часть названия;
12)	Часть значения поля «Sattelities» не влезает в поле по высоте;
13)	В поле «Sattelities» необходимо отображать общее количество спутников (сейчас отображается по каждой Системе ГНСС отдельно);
14)	Нет информации о стабильности антенны (ползунок от 0 до 1);
15)	Если от Ровера поступают одни и те же значения какого-либо параметра то отображается надпись «not available». На самом деле данные от Ровера поступают, только они не меняют своё значение.

**Comment by ISPLab** [comment]
буду править

**Comment by ISPLab** [comment]
В поле «Sattelities» необходимо отображать общее количество спутников (сейчас отображается по каждой Системе ГНСС отдельно);
-текст формируется в плагине

**Comment by ISPLab** [comment]
Значение поля «Heading» перекрывает часть названия;
столько символов после запятой Зачем?

**Comment by kaa1965** [comment]
В поле «Sattelities» необходимо отображать общее количество спутников (сейчас отображается по каждой Системе ГНСС отдельно);
-текст формируется в плагине

Плагин сейчас формирует два события:
- "sattelites_desc" - с детальным описанием количества спутников по всем системам
- "sattelites_count" - общее количество спутников по всем системам ГНСС
UI на странице Съёмка отображает "sattelites_desc", а нужно отображать "sattelites_count"

**Comment by kaa1965** [comment]
Значение поля «Heading» перекрывает часть названия;
столько символов после запятой Зачем?

Плагин передаёт значение в радианах, согласно документации на NVSPoint. Переводить в градусы тогда нужно на UI (с точностью до целого числа в градусах)

nvlir | rover | heading | double | содержит информацию о направлении движения выраженного в радианах | Pic.1
-- | -- | -- | -- | -- | --

**Comment by ISPLab** [comment]
1.
![image](https://user-images.githubusercontent.com/8803512/82779051-cf93bd80-9e5b-11ea-81d9-b99b598fca91.png)

**Comment by ISPLab** [comment]
3. Acurren - invalid width for label

**Comment by ISPLab** [comment]
6. ---нужно по ТЗ (отображать два значения: точность в плане (вычисляется из точностей по широте и долготе) и точность по высоте;
 - значения выставляются в плагине

**Comment by ISPLab** [comment]
Rover time - invalid widht -  
в примерах - указано как возвращать rover time:
        EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.current_time, Convert.ToString(1d), DateTime.Now.ToShortTimeString()));

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82788741-b433ad00-9e71-11ea-8202-ed66d6598676.png)
usage:
   double[] accurency = new double[] { 0.5, 0.2 };
                        var s_accurency = p8Serializer.SerializeToBase64(accurency);
                        EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.accuracy, s_accurency, $""));

**Comment by ISPLab** [comment]
fix
![image](https://user-images.githubusercontent.com/8803512/82789701-6c158a00-9e73-11ea-9b81-418274a51efc.png)

usage
  EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.type_solution, "auto", $""));

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82790204-62405680-9e74-11ea-9526-e5a6bbbfcdf0.png)
usage
  EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.speed, "0.5 m/s", $""));

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82790450-bfd4a300-9e74-11ea-9f9e-61bcdf0979f3.png)
usage
  EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.base_station_distance, "8.54 km", $""));

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82792419-0f689e00-9e78-11ea-899a-4bf4bf49edd3.png)

only "sattelites_desc" - с детальным описанием количества спутников по всем системам
"sattelites_count" - общее количество спутников по всем системам ГНСС
UI на странице Съёмка отображает "sattelites_desc", а нужно отображать "sattelites_count"
will be  removed on documentation
fixed

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/149#issuecomment-633374637

Время от Ровера приходит с точностью до секунды, если Плагин будет передавать в descriptione 23:12:12 - это время нормально отобразится на UI?

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/149#issuecomment-633422153

При передаче события от Плагина:
double[] accureny = new double[] { 0.5, 0.2 };
var s_accurency = p8Serializer.SerializeToBase64(accurency);
EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.accuracy, s_accurency, $""));
строку +-0.5 +-0.2 формирует UI ?
Для чего нужен description в этом событии? Где description отображается?

**Comment by kaa1965** [comment]
Как правильно называется событие (heading или course):
- по документации NVSPoint heading
- по исходникам в demo и плагине course
?

**Comment by kaa1965** [comment]
Как должно формироваться событие rtk_age:
- В Demo так:
double rtk_age = 0.34;
EventBus.Publish(new DemoRoverP8EventData(RoverPluginEvent.rtk_age, Convert.ToString(rtk_age), $""));
- В Документации NVSPoint говорится что Json TimeSpan
Как правильно?

**Comment by ISPLab** [comment]
отправил по почте примеры и актуальные описания всех событий
