### ISSUE TITLE
Страница Surveying (съемка)

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#150]
1)	Ручная съёмка выполняется нормально, если «автоматический режим» выключен.
2)	Автоматическая съёмка выполняется при очередной остановке Ровера и выполнении условий съёмки. Имитация Движения и остановок принималось от РоверИмитатора, который 30 секунд ехал, 30 секунд стоял. 
***
**_Замечания:_**
а)	Не работает настройка «Alias» для наименования точек при выполнении съемки. В экспертных настройках выставляем параметр «Alias»= «P__10_5». То есть точки должны именоваться начиная с пятой с шагом 10. При выполнении съемки точки именуются «p1», «р2» и т.д.

б)	После выполнения ручного и автоматического измерения в диалоговом окне «Alias» не отображается информация о результате измерения.
![Диалог Alias](https://user-images.githubusercontent.com/59056870/82160630-6a5e2c00-989f-11ea-9044-25df265b8ee6.png)
в)	Если в диалоге «Alias» нажать кнопку «Cancel», то точка все равно попадает в Результаты измерений (эти точки видны в экспертных настройках).

г)	Включено автоматическое измерение. ПК подключен к РоверИмитатору, который 30 секунд движется, затем 30 секунд стоит. Т.е. при  очередной остановке выполнится  автоматическое измерение.  При первом измерении открывается диалоговое окно «Alias» с точкой «P1». Пользователь не нажимает никакой кнопки в диалоге «Alias» 4 минуты. По истечению 4х минут нажимает «Accept» в диалоге «Alias» для точки «P1». Открывается окно «Alias» для точки «P2». Опять «Accept» и открывается диалог «Alias» для «P3» и т.д. до «Alias» для «P5» . 
Но Пользователь может и отменить какую-то точку, а названия для следующих уже сформированы.
Наверное, проще и  лучше делать так:
- выполнилось автоматическое измерение,
- появился диалог
- если пользователь нажал cancel – точка не добавляется в Результаты Измерения, если нажал Accept – точка добавляется в Результаты измерения
- и только после этого запускать следующее автоматическое измерение.
Т.е. другими словами если при автоматической съемке открыто диалоговое окно «Alias» для какого-либо измерения, то следующие измерения не должны выполняться до тех пор, пока пользователь не нажмет кнопу «Accept» или «Cancel»

д)	Во время выполнения «автоматической» съемки нет возможности выполнить «ручную». После повторных нажатий на кнопку Start surveying Ручное измерение не выполняется.

е)	Не отображается текущий режим съемки (текущий или автоматический);

ж)	Просмотр Результатов Измерений в экспертном виде вызывает большие сложности. При наличии 10 Результатов Измерений последовательное листание до последней записи требует от Пользователя много времени и операций по листанию. По ТЗ таких точек может быть порядка тысячи.

**Comment by ISPLab** [comment]
весь перечисленный фунционал реализуется Вами в autosurveyingmanager и плагине
За исключением текста о результате измерения
- внесу в следующей build version

**Comment by kaa1965** [comment]
1. В текущей реализации и в той ветке, которая есть у меня autosurveyingmanager никак не связан с Диалогом, которое отображается Пользователю. Тогда их нужно подружить, Чтобы autosurveyingmanager знал, когда Пользователь нажал Accept, а когда Cancel.
2. Метод Initialize autosurveyingmanagerа должен вызываться при:
- смене условий съёмки и правила именования точки (которые определяются в настройках Плагина);
- при переключении переключателя Ручной-автоматический режим съёмки
А сейчас он вызывается при каждом нажатии на кнопку Startsurveying.
Это не позволяет реализовать возможность Ручной съёмки при запущенной Автоматической съемке. Так как счётчик _countStartedSurveyByButton сбрасывается в методе Initialize
3. На данном этапе я так понял никогда не вызывается StopSurveying. Но здесь нужно проанализировать и возможно, он и не нужен, так как перевод в Ручной режим, по сути означает остановку генерации автоматических каких-то событий от Плагина. Вобщем, давай пока по StopSurveying оставим как сейчас, то есть пока и не вызывать его. Может быть StopSurvey вызывать при переключении переключателя Ручной-Автоматический...?? Но давай пока не будем.
ИТОГО: нужно делать 1-е и 2-е....

**Comment by ISPLab** [comment]
1. За исключением текста о результате измерения
внесу в следующей build version
2. autosurveying manager - вызывается при нажатии на кнопку (autosurveying manager)
3. вся актуальная информация в классе на этот момент присутвует
4. согласен с тем что стоп не нужен - если нужен можете сгенерировать событие в плагине и перехватить его в autosurveying manager

**Comment by kaa1965** [comment]
Плагин выполнил Измерение (Ручное или Автоматическое).
Результат Измерения autosurveyingmanager по событию "surveying_result" добавил в список Измерений, вызвав GeoProject.AddsurveyingResult(s_res);
Далее Пользователю показывается Диалог с результатами Измерений.
В Диалоге при нажатии на Cancel ты тогда должен удалить эту точку из  GeoProjecta.

**Comment by kaa1965** [comment]
Сейчас в Диалоге при нажатии на Cancel точка измерений не удаляется из GeoProjecta.

**Comment by ISPLab** [comment]
Cancel (отменить) чтобы закрыть окно без изменений
удаление - крестик

**Comment by ISPLab** [comment]
fixed

**Comment by ISPLab** [comment]
код сохранения точки в проект перенесен из autosurveing manager в диалог

**Comment by ISPLab** [comment]
fix bug
        public List<SurveyingResult> surveyingResults
        {
            get
            {
                var res = this[nameof(surveyingResults)];
                if (res is JContainer)
                {
                    res = new P8Serializer().DeserializeFromString<List<SurveyingResult>>(res.ToString());
                }
                return  (List <SurveyingResult> )res;
            }
            set { this[nameof(surveyingResults)] = value; }
        }
