### ISSUE TITLE
Отображение текущих параметров в экспертном меню

### ISSUE THREAD

**Issue by tipin1** [ISPLab/P8#151]
Во время работы в экспертных настройках Плагина появляется блок данных Changed. Что это за Блок данных? Пользователь их может изменить!!!!! Зачем?

**Comment by ISPLab** [comment]
фото пришлите

**Comment by tipin1** [comment]
Ссылка на видео https://cloud.mail.ru/public/P6Wv/5j5384KSv

**Comment by ISPLab** [comment]
Это системное значение, изменение его не повлияет на работу плагина,
чтобы его изменить/просмотреть нужно понимать как работает модель представления
Системные значения после отладки и тестирования будут убраны
