### ISSUE TITLE
GetAppereanceCoordinate

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#152]
GetAppereanceCoordinate должна возвращать 3 координаты.
Третью координату также нужно отображать после пересчёта в этой функции.
Ниже тесты, которые показывают результаты перевода координат из WGS84 в СК95:
Высота над элипсоидом WGS84 = 202.73
А Высота над элипсоидом СК95 = 196,1603
Естественно они разные, так как элипсоид в каждой СК со своими размерами.
Поэтому убирай наименование поля для высоты. И отображай две координаты как и сейчас, третью без названия ниже (потому что высота в XYZ это неправильно).
Лучше, если для каждой координаты в зависимости от Типа представления отображать ещё и её название.
Сообщаю в очередной раз о том, что названия координат следующие:
Для BLH: φ λ h
Для XYZ: X Y Z
Для NEH: x y h
Как вариант три координаты в трёх строчках.
И ещё - Заказчику важно измерить высоту в его СК, так как труба Заказчика в основном проседает по высоте и именно это проседание он контролирует.

[Test]
        public void GetAppereanceCoordinateWGS84_CK95_BLH()
        {
            GeoProject geoProject = new GeoProject();
            geoProject.ProjectDatum.Datum = GeoWrapper.GetDatum(DatumId.CK95);
            geoProject.Parameters.GeoPresentationType = GeoPresentationType.BLH_Deg;

            double[] p1 = new double[] { 55.835801, 37.972990 };
            p1 = ToRadians(p1);
            p1[2] = 202.73;//метры

            string str = geoProject.GetAppereanceCoordinate(p1);

            Assert.IsTrue(str == "55,835734559N 37,974840845E 196,1603");
        }

[Test]
        public void GetAppereanceCoordinateWGS84_CK95_NEH()
        {
            GeoProject geoProject = new GeoProject();
            geoProject.ProjectDatum.Datum = GeoWrapper.GetDatum(DatumId.CK95);
            geoProject.Parameters.GeoPresentationType = GeoPresentationType.NEH_Meter;

            double[] p1 = new double[] { 55.835801, 37.972990 };
            p1 = ToRadians(p1);
            p1[2] = 202.73;

            string str = geoProject.GetAppereanceCoordinate(p1);

            Assert.IsTrue(str == "6190857,5954 435766,6439 196,1603");
        }
[Test]
        public void GetAppereanceCoordinateWGS84_CK95_XYZ()
        {
            GeoProject geoProject = new GeoProject();
            geoProject.ProjectDatum.Datum = GeoWrapper.GetDatum(DatumId.CK95);
            geoProject.Parameters.GeoPresentationType = GeoPresentationType.XYZ_Meter;

            double[] p1 = new double[] { 55.835801, 37.972990 };
            p1 = ToRadians(p1);
            p1[2] = 202.73;

            string str = geoProject.GetAppereanceCoordinate(p1);
            
            Assert.IsTrue(str == "2830055,0954 2209080,7921 5254447,8448");
        }

**Comment by ISPLab** [comment]
да вчера это обсудили по телефонy
то что заказчику нужно то и возвращайте  через GetAppereanceCoordinate в geoproject
(по умолчанию xyz wgs84)
