### ISSUE TITLE
Conversiton coordinates 

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#153]
![image](https://user-images.githubusercontent.com/8803512/82178375-791b0200-98e4-11ea-8f35-8bbb738eec51.png)

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82178637-1fff9e00-98e5-11ea-86db-dc30ee0e9fa9.png)

![image](https://user-images.githubusercontent.com/8803512/82178606-1118eb80-98e5-11ea-8bf7-07b38d398319.png)

**Comment by ISPLab** [comment]
вывод результатов не совпадает

**Comment by kaa1965** [comment]
Функция GetAppereanceCoordinate использует установленные значения параметров Датума и Проекции Проекта. 
Какие параметры установлены для Датума и Проекции Проекта?

**Comment by ISPLab** [comment]
По умолчанию все
Что написать, чтобы получить результат как представлен выше?

**Comment by kaa1965** [comment]
Всё совпадает в библиотеке Кузьмицкого для Проекции UTM 38 зона:

[Test]
        public void GetAppereanceCoordinateWGS84_UTM_NEH()
        {
            GeoProject geoProject = new GeoProject();
            geoProject.ProjectDatum.Datum = GeoWrapper.GetDatum(DatumId.WGS84);
            int numberZone = 38;
            char hemisphere = 'N';
            geoProject.ProjectProjection.Projection = GeoWrapper.GetUTMprojection(numberZone, hemisphere);
            geoProject.Parameters.GeoPresentationType = GeoPresentationType.NEH_Meter;

            double[] p1 = new double[] { 51.2299, 47.60443 };
            
            p1 = ToRadians(p1);
            p1[2] = 0;

            string str = geoProject.GetAppereanceCoordinate(p1);
            
            //С сайта:
            //https://www.sunearthtools.com/dp/tools/conversion.php?lang=en
            //UTM: (Universal Transverse Mercator)
            //Zone: 38
            //X (easting): 681833.726
            //Y(northing): 5678614.262

            Assert.IsTrue(str == "5678614,262 681833,7261 -0,");
        }

**Comment by ISPLab** [comment]
Что написать в проекте, чтобы получить результат как представлен выше? 
Пришлите фото с проекта (или проект) из nvspoint

**Comment by kaa1965** [comment]
Нужно установить следующие значения:
1. Установить параметры Датума:

  | Name | Value | Type
-- | -- | -- | --
◢ | geoProject.ProjectDatum.Datum | {P8.Geo.datum_t} | P8.Geo.datum_t
  | ◢ ellipsoid | {P8.Geo.ellipsoid_t} | P8.Geo.ellipsoid_t
  | flattening | 0.0033528106647474805 | double
  | majoraxis | 6378137 | double
  | ◢ origin | {P8.Geo.origin_t} | P8.Geo.origin_t
  | dx | 0 | double
  | dy | 0 | double
  | dz | 0 | double
  | sf | 0 | double
  | wx | 0 | double
  | wy | 0 | double
  | wz | 0 | double

2. Установить параметры проекции:

  | Name | Value | Type
-- | -- | -- | --
◢ | geoProject.ProjectProjection.Projection | {P8.Geo.projection_t} | P8.Geo.projection_t
  | Az | 0 | double
  | Bo | 0 | double
  | Eo | 500000 | double
  | F | 0.9996 | double
  | Lo | 0.78539816339744828 | double
  | No | 0 | double
  | @type | 1 | P8.Geo.ProjectionType //TRANSVERSE_MERCATOR

3. Установить тип представления координат:

  | geoProject.Parameters.GeoPresentationType | 4 |

**Comment by kaa1965** [comment]
Да всё правильно

**Comment by kaa1965** [comment]
Только вот сейчас enum  у меня имеет уже такие значения:
public enum GeoPresentationType
    {
        DS = 0,  // Геодезические BLH-градусы БЕЗ знака на конце (N-S E-W), спереди может быть "минус" 40.7600000 73.9840000
        DD = 1,  // Геодезические BLH-градусы на конце знак (N-S E-W) 40.7600000N 73.9840000E
        DM = 2,  // Геодезические BLH-градусы-минуты конце знак (N-S E-W) 40°45.647’N , 73°59.045’E
        DMS = 3, // Геодезические BLH-градусы-минуты-секунды конце знак (N-S E-W) 40°45´36"N 73°59´2.4"E
        XYZ = 4, // геоцентрические XYZ (от Центра Земли в метрах) 45000,123
        NEH = 5,  // местные координаты (расстояние от какого то меридиана) спереди может быть "минус" 45000,123
        PROJECT = 6 //Тип представления задаётся в Проекте из числа выше перечисленных
    }

**Comment by ISPLab** [comment]
check after merge
