### ISSUE TITLE
set default rover position

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#154]
Нужна ли настройка в Preferences (позиция ровера), если ровер не подключен,
чтобы отображались объекты на карте?

**Comment by ISPLab** [comment]
Или еще можно сделать чтобы карта устанавливалась по точке проекта, (если ровер не подключен)

**Comment by kaa1965** [comment]
Нужна ли настройка в Preferences (позиция ровера), если ровер не подключен,
чтобы отображались объекты на карте?

Что будет делать эта настройка? Включать-выключать рисование Ровера на карте? Или центрировать Ровер на карте?
Настройка центрировать или не центрировать на карте по местоположению Ровера - точно нужна.

Настройка выключать и включать рисование Ровера на карте - тоже нужна, так как при работе с точками проекта это пригодится.

**Comment by kaa1965** [comment]
Или еще можно сделать чтобы карта устанавливалась по точке проекта, (если ровер не подключен)
Должен быть список с точками проекта, Пользователь там должен выбрать точку и выполнить операцию "Показать на карте".
То что касается ситуации когда ровер не подключен, наверное нужно говорить о том, с чем Пользователь работает и какие задачи хочет решить.

**Comment by ISPLab** [comment]
Это Issue был вопрос был по инициализации карты.
Сделана установка по объекту на точке
функцию показать на карте если необходима можете добавить в новый issue для обсуждения

**Comment by kaa1965** [comment]
По твоему вопросу не скажешь что вопрос был по инициализации карты:
**Нужна ли настройка в Preferences (позиция ровера), если ровер не подключен,
чтобы отображались объекты на карте?**

Тогда встречный вопрос: а Инициализация карты выполняется при запуске программы или в течение работы тоже? Если в процессе работы выполняется то когда?
Если рассуждать логически, то при запуске программы вряд ли уже придут координаты от Ровера, они придут чуть позже, даже если был включен Автозапуск.

Тогда, может быть, карту нужно центрировать по последнему Измерению, а если и его нет тогда по первой точке Проекта...

Было бы супер иметь возможность центрировать по координатам, которые вводит Пользователь, но этого в ТЗ нет, да и не ко времени, но иметь ввиду на будущее можно...
