### ISSUE TITLE
GetDistance function

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#155]
/// <summary>
        /// Get distance between two coordinate
        /// </summary>
        /// <param name="coordinate1">double[] coordinate value </param>
        /// <param name="coordinate2">double[] coordinate value</param>
        /// <returns>distance in metters, angle in radinans</returns>
        Tuple<double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2 datum_projection_format_zone)
        {
            return new Tuple<double, double>(2300, 34);
        }

**Comment by ISPLab** [comment]
Функция в соответсвии с ConvertCoordinate ?

**Comment by kaa1965** [comment]
Tuple<double, double>(2300, 34);
2300 - расстояние между точками в метрах?
34 - Азимут - угол между двумя линиями. Первая линия от первой точки на Север. Вторая линия первой точки до второй точки. Угол в градусах от 0-360
Так?

**Comment by kaa1965** [comment]
1. Не хватает одного входного параметра, который бы задавал как выполняется измерение: на в Плане или в Ортодро́мии (по дуге на шаре);
2. Функция должна возвращать три значения:
- Дистанция в метрах
- Азимут - угол между двумя линиями. Первая линия от первой точки на Север. Вторая линия от первой точки до второй точки. Угол в градусах от 0-360
- Превышение по высоте второй точки относительно первой в метрах.
3. Предлагаю такую спецификацию функции:
double[] GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2, string datum_projection_format_zone, bool orthodromy)
Функция возвращает double[3] - порядок значений, как в пункте 2.
        Примечание: в geo.dll предоставляется две разные функции:
- inverse_problem_orthodromy
- inverse_problem_inplane

**Comment by kaa1965** [comment]
На входе функции жду градусы(НЕ РАДИАНЫ) или метры:
double[] GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2, string datum_projection_format_zone, bool orthodromy)

**Comment by kaa1965** [comment]
Выслал тесты по почте

**Comment by ISPLab** [comment]
формат передачи градусов в программе - радианы
при вводе в градусах - на все ui стоят конвекторы в rad 
на элементах отображения - конвекторы в градусы

**Comment by ISPLab** [comment]
Не хватает одного входного параметра, который бы задавал как выполняется измерение: на в Плане или в Ортодро́мии (по дуге на шаре);
 -  результаты разные  получаются?

**Comment by kaa1965** [comment]
Да разные, если задавать большие расстояния. Это нужно по Требованиям от Заказчика и по ПМИ

**Comment by kaa1965** [comment]
На входе функции coordinate1, coordinate2 - в радианах или метрах:
bool orthodromy - true - по Ортодро́мии, false - в Плане
double[] GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2, string datum_projection_format_zone, bool orthodromy)
Так?

**Comment by ISPLab** [comment]
NVSPoint check result test:
     public void Angle0Test()
        {
            double[] p1 = new double[] { 51.22986, 47.60443 };//lower
            double[] p2 = new double[] { 51.2299, 47.60443 };//higher
          
            var angle = //
            var dist = //
            Assert.IsTrue(Math.Round(dist, 2) == 4.45);
            Assert.IsTrue(Math.Round(angle, 2) == 0);
        }

**Comment by ISPLab** [comment]
Tuple<double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2, string datum_projection_format_zone, bool orthodromу=false)

**Comment by kaa1965** [comment]
Сделал два теста
Вычисление по Ортодромии даёт отличные результаты и по дистанции и по курсу:
[Test]
        public void Angle0_Orthodromy_Test()
        {
            GeoProject geoProject = new GeoProject();
            double[] p1 = new double[] { 51.22986, 47.60443, 0 };//lower
            p1[0] = P8.Geo.units.deg2rad(p1[0]);
            p1[1] = P8.Geo.units.deg2rad(p1[1]);
            double[] p2 = new double[] { 51.2299, 47.60443, 0 };//higher
            p2[0] = P8.Geo.units.deg2rad(p2[0]);
            p2[1] = P8.Geo.units.deg2rad(p2[1]);

            int numberZone = 38;
            //string input_datum_projection_desc = string.Format("{0}_{1}_{2}_{3}", DatumIdEx.WGS84, GeoProjectionIdEx.UTM, GeoPresentationType.XYZ, numberZone);
            string datum_projection_desc1 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            string datum_projection_desc2 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            bool orthodromy = true;
            double[] dist_az_deltah = geoProject.GetDistatance(p1, datum_projection_desc1, p2, datum_projection_desc2, orthodromy);

            var dist = dist_az_deltah[0];
            var angle = dist_az_deltah[1];

            Assert.IsTrue(Math.Round(dist, 2) == 4.45);
            Assert.IsTrue(Math.Round(angle, 2) == 0);

            Assert.IsTrue(dist == 4.450107004731974);
            Assert.IsTrue(angle == 0);
            Assert.IsTrue(dist_az_deltah[2] == 0);
        }

Вычисление в Плане даёт отличные результаты по Дистанции, но курс на 2 градуса отличается:

 [Test]
        public void Angle0_Plane_Test()
        {
            GeoProject geoProject = new GeoProject();
            double[] p1 = new double[] { 51.22986, 47.60443, 0 };//lower
            p1[0] = P8.Geo.units.deg2rad(p1[0]);
            p1[1] = P8.Geo.units.deg2rad(p1[1]);
            double[] p2 = new double[] { 51.2299, 47.60443, 0 };//higher
            p2[0] = P8.Geo.units.deg2rad(p2[0]);
            p2[1] = P8.Geo.units.deg2rad(p2[1]);

            int numberZone = 38;
            //string input_datum_projection_desc = string.Format("{0}_{1}_{2}_{3}", DatumIdEx.WGS84, GeoProjectionIdEx.UTM, GeoPresentationType.XYZ, numberZone);
            string datum_projection_desc1 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            string datum_projection_desc2 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            bool orthodromy = false;
            double[] dist_az_deltah = geoProject.GetDistatance(p1, datum_projection_desc1, p2, datum_projection_desc2, orthodromy);

            var dist = dist_az_deltah[0];
            var angle = dist_az_deltah[1];

            Assert.IsTrue(Math.Round(dist, 2) == 4.45);
            Assert.IsTrue((360 - angle) < 2.1);
                        
            Assert.IsTrue(dist == 4.4501336302078727);
            Assert.IsTrue(angle == 357.96886523321604);
            Assert.IsTrue(dist_az_deltah[2] == 0);
        }

**Comment by kaa1965** [comment]
Tuple<double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2, string datum_projection_format_zone, bool orthodromу=false)
Никак нельзя им без высоты сравнивать две точки, для них это важно!!!!!! и в ПМИ включено.
Функция должна возвращать три параметра, третий превышение по высоте между точками.

**Comment by ISPLab** [comment]
Tuple<double, double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone, double [] coordinate2, string datum_projection_format_zone, bool orthodromу=false)

**Comment by ISPLab** [comment]
тогда

**Comment by kaa1965** [comment]
Сделал
public Tuple<double, double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone1,
            double[] coordinate2, string datum_projection_format_zone2, bool orthodromy = true)      
Функция возвращает:
Item1 - Дистанция в метрах
Item2 - **ГРАДУСЫ 0-360!!!!!!!**
Item3 - Превышение по высоте в метрах (**положительное-вторая точка выше, отрицательное-вторая точка ниже**)

**Comment by kaa1965** [comment]
[Test]
        public void CalcDistanceWGS84UTMDS_WGS84UTMDS_plane()
        {
            GeoProject geoProject = new GeoProject();

            //Координаты XYZ в СК WGS84 точки Lat=51.2299 Lon=47.60443 H=203.7;//метров            
            double[] inputCoordinate1 = new double[3] { 51.22986, 47.60444, 207.179 };
            inputCoordinate1[0] = P8.Geo.units.deg2rad(inputCoordinate1[0]);
            inputCoordinate1[1] = P8.Geo.units.deg2rad(inputCoordinate1[1]);
            double[] inputCoordinate2 = new double[3] { 51.229899695225107, 47.60444, 225.179 };
            inputCoordinate2[0] = P8.Geo.units.deg2rad(inputCoordinate2[0]);
            inputCoordinate2[1] = P8.Geo.units.deg2rad(inputCoordinate2[1]);

            int numberZone = 38;
            //string input_datum_projection_desc = string.Format("{0}_{1}_{2}_{3}", DatumIdEx.WGS84, GeoProjectionIdEx.UTM, GeoPresentationType.XYZ, numberZone);
            string datum_projection_desc1 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            string datum_projection_desc2 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            bool orthodromy = false;
            Tuple<double, double, double> dist_az_deltah = geoProject.GetDistatance(inputCoordinate1, datum_projection_desc1, inputCoordinate2, datum_projection_desc2, orthodromy);

            var dist = dist_az_deltah.Item1;
            var angle = dist_az_deltah.Item2;
            var deltaH = dist_az_deltah.Item3;

            Assert.IsTrue(dist == 4.4162264193072254);//Дистанция в метрах
            Assert.IsTrue(angle == 357.96885743779518);//ГРАДУСЫ 0-360!!!!!!!
            Assert.IsTrue(deltaH == 18);//Превышение по высоте в метрах
        }
        [Test]
        public void CalcDistanceWGS84UTMDS_WGS84UTMDS_orthodromy()
        {
            GeoProject geoProject = new GeoProject();

            //Координаты XYZ в СК WGS84 точки Lat=51.2299 Lon=47.60443 H=203.7;//метров            
            double[] inputCoordinate1 = new double[3] { 51.22986, 47.60444, 207.179 };
            inputCoordinate1[0] = P8.Geo.units.deg2rad(inputCoordinate1[0]);
            inputCoordinate1[1] = P8.Geo.units.deg2rad(inputCoordinate1[1]);
            double[] inputCoordinate2 = new double[3] { 52.229899695225107, 48.60444, 225.179 };
            inputCoordinate2[0] = P8.Geo.units.deg2rad(inputCoordinate2[0]);
            inputCoordinate2[1] = P8.Geo.units.deg2rad(inputCoordinate2[1]);

            int numberZone = 38;
            //string input_datum_projection_desc = string.Format("{0}_{1}_{2}_{3}", DatumIdEx.WGS84, GeoProjectionIdEx.UTM, GeoPresentationType.XYZ, numberZone);
            string datum_projection_desc1 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            string datum_projection_desc2 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            bool orthodromy = false;
            Tuple<double, double, double> dist_az_deltah = geoProject.GetDistatance(inputCoordinate1, datum_projection_desc1, inputCoordinate2, datum_projection_desc2, orthodromy);

            var dist = dist_az_deltah.Item1;
            var angle = dist_az_deltah.Item2;
            var deltaH = dist_az_deltah.Item3;

            Assert.IsTrue(dist == 130991.2323056243);//Дистанция в метрах
            Assert.IsTrue(angle == 29.398998960525841);//ГРАДУСЫ 0-360!!!!!!!
            Assert.IsTrue(deltaH == 18);//Превышение по высоте в метрах
        }

        [Test]
        public void Angle0_Orthodromy_Test()
        {
            GeoProject geoProject = new GeoProject();
            double[] p1 = new double[] { 51.22986, 47.60443, 0 };//lower
            p1[0] = P8.Geo.units.deg2rad(p1[0]);
            p1[1] = P8.Geo.units.deg2rad(p1[1]);
            double[] p2 = new double[] { 51.2299, 47.60443, 0 };//higher
            p2[0] = P8.Geo.units.deg2rad(p2[0]);
            p2[1] = P8.Geo.units.deg2rad(p2[1]);

            int numberZone = 38;
            //string input_datum_projection_desc = string.Format("{0}_{1}_{2}_{3}", DatumIdEx.WGS84, GeoProjectionIdEx.UTM, GeoPresentationType.XYZ, numberZone);
            string datum_projection_desc1 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            string datum_projection_desc2 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            bool orthodromy = true;
            Tuple<double, double, double> dist_az_deltah = geoProject.GetDistatance(p1, datum_projection_desc1, p2, datum_projection_desc2, orthodromy);

            var dist = dist_az_deltah.Item1;
            var angle = dist_az_deltah.Item2;
            var deltaH = dist_az_deltah.Item3;

            Assert.IsTrue(Math.Round(dist, 2) == 4.45);
            Assert.IsTrue(Math.Round(angle, 2) == 0);

            Assert.IsTrue(dist == 4.450107004731974);//Дистанция в метрах
            Assert.IsTrue(angle == 0);//ГРАДУСЫ 0-360!!!!!!!
            Assert.IsTrue(deltaH == 0);//Превышение по высоте в метрах
        }

        [Test]
        public void Angle0_Plane_Test()
        {
            GeoProject geoProject = new GeoProject();
            double[] p1 = new double[] { 51.22986, 47.60443, 0 };//lower
            p1[0] = P8.Geo.units.deg2rad(p1[0]);
            p1[1] = P8.Geo.units.deg2rad(p1[1]);
            double[] p2 = new double[] { 51.2299, 47.60443, 0 };//higher
            p2[0] = P8.Geo.units.deg2rad(p2[0]);
            p2[1] = P8.Geo.units.deg2rad(p2[1]);

            int numberZone = 38;
            //string input_datum_projection_desc = string.Format("{0}_{1}_{2}_{3}", DatumIdEx.WGS84, GeoProjectionIdEx.UTM, GeoPresentationType.XYZ, numberZone);
            string datum_projection_desc1 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            string datum_projection_desc2 = string.Format("{0}_{1}_{2}_{3}", "WGS84", "UTM", "DS", numberZone);
            bool orthodromy = false;
            Tuple<double, double, double> dist_az_deltah = geoProject.GetDistatance(p1, datum_projection_desc1, p2, datum_projection_desc2, orthodromy);

            var dist = dist_az_deltah.Item1;
            var angle = dist_az_deltah.Item2;
            var deltaH = dist_az_deltah.Item3;

            Assert.IsTrue(Math.Round(dist, 2) == 4.45);
            Assert.IsTrue((360 - angle) < 2.1);
                        
            Assert.IsTrue(dist == 4.4501336302078727);//Дистанция в метрах
            Assert.IsTrue(angle == 357.96886523321604);//ГРАДУСЫ 0-360!!!!!!!
            Assert.IsTrue(deltaH == 0);//Превышение по высоте в метрах
        }

**Comment by kaa1965** [comment]
У нас в функцию GetCoordinate в параметре angleInRadian передаётся азимут в радианах
https://github.com/ISPLab/P8/issues/156#issuecomment-633293112
вот в обратной функции GetDistance в возвращаемом Tuple<double, double, double> dist_az_deltah возвращается азимут на вторую точку в градусах
Переделываю GetDistance  чтобы тоже возвращал радианы?

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82817884-71d89300-9ea6-11ea-9402-a2de14ffb4e1.png)

**Comment by ISPLab** [comment]
все возвращается в радианах

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82818929-2c1cca00-9ea8-11ea-9d97-1437bcd15d43.png)

**Comment by kaa1965** [comment]
Теперь GetDistatance возвращает Азимут в радианах,
Функция Возвращает
Item1-Дистанция в метрах, Item2-Азимут в радианах, Item3-Превышение по 

public Tuple<double, double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone1,
            double[] coordinate2, string datum_projection_format_zone2, bool orthodromy = true)
Тесты по почте

**Comment by ISPLab** [comment]
/// <summary>
        /// Возвращает Item1-Дистанция в метрах, Item2-Азимут в радианах, Item3-Превышение по высоте в метрах 
        /// </summary>        
        public Tuple<double, double, double> GetDistatance(double[] coordinate1, string datum_projection_format_zone1,
            double[] coordinate2, string datum_projection_format_zone2, bool orthodromy = true)
        {

релизовано неверно

**Comment by kaa1965** [comment]
Что конкретно неверно?
