### ISSUE TITLE
Calculate Coordinate function

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#156]
/// <summary>
        /// GetCoordinate
        /// </summary>
        public double[] GetCoordinate (double[] coordinate, double dist, double angle, string datum_pjojction_format)
        {
            throw new NotImplementedException();
        }

**Comment by ISPLab** [comment]
[Test]
        public void GetCoordinateFunctionTest()
        {
            double[] p1 = new double[] { 51.22986, 47.60443 };//lower
            double[] true_coordinate = new double[] { 51.2299, 47.60443 };//higher
            double[] coordinate = GetCoordinate(p1, 4.45, 0, "WGS84_UTM_DS");
            string s = "";
            Assert.IsTrue(p1.Equals(coordinate));
        }

**Comment by ISPLab** [comment]
потом надо будет обсудить ввод input_datum_proj_format

**Comment by kaa1965** [comment]
не хватает входных параметров:
- превышения по высоте
- признака : в Плане или Ортодромии

**Comment by ISPLab** [comment]
DS DMS DD можно заменить на rad 
тогда получится - WGS84_UTM_Rad
или 
 WGS84_UTM_Meters

**Comment by ISPLab** [comment]
не хватает входных параметров:

превышения по высоте
признака : в Плане или Ортодромии

Чему не хватает?

**Comment by ISPLab** [comment]
на нуле (на одной высоте) сравнивать не может?

**Comment by kaa1965** [comment]
Функция должна быть такой, иначе я не смогу получить координаты второй точки и вернуть их:
public double[] GetCoordinate (double[] coordinate, double dist, double angle, double deltaH, string datum_pjojction_format, bool orthodromy)

**Comment by ISPLab** [comment]
double deltaH - может быть неизвестна 
public double[] GetCoordinate (double[] coordinate, double dist, double angle, string datum_pjojection_format, bool orthodromy=true, double deltaH = 0)

**Comment by ISPLab** [comment]
давайте сейчас к парсеру вернемся
Parsing entering coordinate for geo project point #133

**Comment by kaa1965** [comment]
Добавил Зону в datum_pjojection_format_zone. Параметры по умолчанию - ОК.
public double[] GetCoordinate (double[] coordinate, double dist, double angle, string datum_pjojection_format_zone, bool orthodromy=true, double deltaH = 0)
double angle - **в градусах ?????**

**Comment by kaa1965** [comment]
**Не хватает ещё выходного формата:** 
public double[] GetCoordinate (double[] coordinate, double dist, double angle, string input_datum_pjojection_format_zone, output_datum_pjojection_format_zone, bool orthodromy=true, double deltaH = 0)

**Comment by ISPLab** [comment]
в градусах ????? radinans

**Comment by kaa1965** [comment]
Хорошо. Итого:
dist - расстояние от первой точки до второй в метрах
angle - угол в радианах между направлением на Север от первой точки и линией от первой до второй точки
deltaH - превышение второй точки по отношению к первой (отрицательное значение - вторая точка ниже первой)
public double[] GetCoordinate (double[] coordinate, double dist, double angle, string input_datum_pjojection_format_zone, output_datum_pjojection_format_zone, bool orthodromy=true, double deltaH = 0)

**Comment by ISPLab** [comment]
сначала 
Parsing entering coordinate for geo project point #133
с этим определимся

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/156#issuecomment-633050795
А как у тебя будет?
Пользователь вводит градусы для angle
далее ты конвертишь в радианы, и уже радианы передашь GetCoordinate?
Пользователь же не должен радианы вводить

**Comment by kaa1965** [comment]
Реализована функция. Тесты отправил по почте
Вычисляет координаты новой точки
"coordinate">Координаты для DS,DD,DM,DMS в радианах, для всего остального метры
"dist">Расстояние в метрах от первой точки до второй
**"angleInRadian">Радианы** Угол Между Направлением на Север и Линией ко второй точке "input_datum_pjojection_format_zone"></param>
"output_datum_pjojection_format_zone"></param>
"orthodromy">true-ортодромия false - в плане</param>
"deltaH">Превышение по высоте (отрицательное значение означает, что вторая точка ниже первой)
Вычисляет координаты новой точки на Датуме Проекции согласно Типу представления в input_datum_pjojection_format_zone
Возвращает координаты согласно Датуму Проекции и Типу представления в output_datum_pjojection_format_zone
        public double[] GetCoordinate(double[] coordinate, double dist, double angleInRadian, string input_datum_pjojection_format_zone, string output_datum_pjojection_format_zone,
            bool orthodromy = true, double deltaH = 0)

**Comment by ISPLab** [comment]
Covert Coordinate UI
![image](https://user-images.githubusercontent.com/8803512/82816426-cb8b8e00-9ea3-11ea-9b0d-c6d0529ec454.png)

**Comment by ISPLab** [comment]
![image](https://user-images.githubusercontent.com/8803512/82818569-95e8a400-9ea7-11ea-8c0c-9bf8b947def2.png)
