### ISSUE TITLE
express format coordinate

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#157]
double[] Coordinate = new ....
  double[1] is latitude or x 
  double[2] is longitude or y
  double[3] is height (meters)
  double[4] id datum
  double [5] is projection
  double[6] is format 
  double[7] is zone 

string ToDS(this double[])
{
return //coordinate in ds
}
string ToDD(this double[])
string ToDMS(this double[])
string ToXYZ(this double[])
string ToFormat(this double[])
{
return //from  double[6]  {format} 
}

**Comment by kaa1965** [comment]
В каком классе эти функции делать?

**Comment by ISPLab** [comment]
в любом

**Comment by ISPLab** [comment]
according p8 entering coordinate format specification
https://docs.google.com/document/d/1EBxs96jNLXTjz832dEvYOJYBz3vQeJf4CdsVIXOM5AA/edit?usp=sharing

**Comment by kaa1965** [comment]
Функции реализованы в классе public partial class GeoProject (GeoProjectEx.cs):
public string ToDS(double[] coordinate)
public string ToDD(double[] coordinate)
public string ToDM(double[] coordinate)
public string ToDMS(double[] coordinate)
public string ToXYZ(double[] coordinate)
public string ToNEH(double[] coordinate)
public string ToFormat(double[] coordinate)
Тесты по почте

**Comment by kaa1965** [comment]
Внесена коррекция в методы.
В ситуациях когда передаётся число, например 213.0000007, то после округления получалось 213.000, затем выполнялось обрезание незначащих правых нулей и получалось 213. (то есть оставалась точка без десятичных цифр)
Теперь формируется строка: 213.0

**Comment by kaa1965** [comment]
1. В связи с появлением данных методов (ToDS и т.д.)
функция internal string GetAppereanceCoordinate(double[] position)
теперь использует эти методы. Ранее функция GetAppereanceCoordinate формировала строки  для координат по своим правилам (которые отличались от правил в этих методах).
2. Функция GetAppereanceCoordinate перенесена из GeoProject.cs в другой partial в файл GeoProjectEx.cs
