### ISSUE TITLE
wrongs fixes? 

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#159]
geoProject.Parameters.GeoPresentationType = GeoPresentationType.DM;//Отображение координат - В местной системе координат пользователя

**Comment by ISPLab** [comment]
GeoPresentationType.DM - не NEH???

**Comment by ISPLab** [comment]
Parameters.GeoPresentationType = GeoPresentationType.BLH_Deg;//Отображение координат - В местной системе координат пользователя

**Comment by kaa1965** [comment]
GeoPresentationType.DM - не NEH???
GeoPresentationType.DM - это координаты для Типа представления ГРАДУСЫ-МИНУТЫ, которое требуется реализовать по Требованиям ТЗ:
55°45.647’N , 37°39.045’E

**Comment by kaa1965** [comment]
Parameters.GeoPresentationType = GeoPresentationType.BLH_Deg;
Это старое значение Enuma GeoPresentationType, в новой редакции такого нет

**Comment by ISPLab** [comment]
public GeoProject()
        {
            Name = string.Empty;
            AutoSurveying = false;
            //   ProjectDatum.Datum=  GeoWrapper.GetDatum(P8.Geo.DatumId.WGS84);
            //   ProjectDatum.Description = "WGS84";

            GeoPoints = new List<GeoProjectPoint>();
            surveyingResults = new List<SurveyingResult>();

            //AliasPolicy = new Func<string>(() =>
            //{
            //    return $"p{ surveyingResults.Count + 1} ";
            //});
            AliasPolicy = GetAliasPoint;

**Comment by ISPLab** [comment]
AliasPolicy = GetAliasPoint;  Почему не в autoserveying присвоение?

**Comment by ISPLab** [comment]
GeoPresentationType.DM - это координаты для Типа представления ГРАДУСЫ-МИНУТЫ, которое требуется реализовать по Требованиям ТЗ:
55°45.647’N , 37°39.045’E 
а с DMS не перепутали?

**Comment by ISPLab** [comment]
которое требуется реализовать по Требованиям ТЗ:
фомата DM - в ТЗ нет

**Comment by ISPLab** [comment]
которое требуется реализовать по Требованиям ТЗ:
фомата DM - в документации тоже

**Comment by kaa1965** [comment]
GeoPresentationType.DM - это координаты для Типа представления ГРАДУСЫ-МИНУТЫ, которое требуется реализовать по Требованиям ТЗ:
55°45.647’N , 37°39.045’E
а с DMS не перепутали?

GeoPresentationType.DMS - это координаты для Типа представления "**градусы-минуты-СЕКУНДЫ**":
55°45'5.647’'N , 37°3'25.045'’E

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/159#issuecomment-634462643
Вот ТЗ:
7.1.3.1. Должна обеспечиваться возможность настройки отображения и ввода геодезических координат (широты, долготы) в следующих форматах:
–	ГГГ° ММ' СС.СССС" **- (=DMS)**
–	ГГГ°ММ.ММММММ' **- (=DM)**
–	ГГГ.ГГГГГГГГГГГГ° **- (=DD)**
Для указания направления  (север, юг, запад восток) должны применяться символы С, Ю, З, В либо N, S, W, E.

**Comment by ISPLab** [comment]
Вот ТЗ: 7.1.3.1. --нет такого пункта

![image](https://user-images.githubusercontent.com/8803512/82988395-c5abbf00-a001-11ea-9370-8091c9304643.png)

**Comment by ISPLab** [comment]
DM - будет внесено в документацию

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/159#issuecomment-634471943

Выслал ТЗ по почте см. стр.22

**Comment by ISPLab** [comment]
уже высылали (9 декабря)

**Comment by kaa1965** [comment]
https://github.com/ISPLab/P8/issues/159#issuecomment-634461541
На данный момент функция, которая формирует название конкретного Измерения одна. Во время работы она не меняется. Поэтому её определение вынесено в конструктор:
AliasPolicy = GetAliasPoint
Если что-то не складывается, можно и перенести, главное чтобы работало

**Comment by ISPLab** [comment]
так конем тоже не ходят
мы согласовывали autosuveying result

**Comment by kaa1965** [comment]
Стоп.
Понятно почему сейчас не складывается с парсером.
Я же тебе говорил, что внесены коррекции в парсер, но мне нужно запушить эти изменения....

**Comment by ISPLab** [comment]
я его уже почти сделал

**Comment by ISPLab** [comment]
и кое-как смержил , договаривались что до вчерашнего вечера будем вносить изменения

**Comment by kaa1965** [comment]
Так ты сказал, что скажешь, когда можно будет пушить, я и ждал

**Comment by ISPLab** [comment]
сказал и писал что до вечера
