### ISSUE TITLE
 login Russian ПС invalid for web uri standart

### ISSUE THREAD

**Issue by ISPLab** [ISPLab/P8#81]

**Comment by kaa1965** [comment]
На Сервере реализованы Точки монтирования, к которым и выполняется подключение с ПК. При подключении к ПК указывается Точка монтирования. Все точки монтирования на данном этапе определяются на латинице

**Comment by ISPLab** [comment]
есть возможность воспользоваться физической клавиатурой
в завтрашней верссии клавиатура русская клавиатура включена (с неверной привязкой к экрану) (in progress)
