### ISSUE TITLE
Размеры окна Программы

### ISSUE THREAD

**Issue by kaa1965** [ISPLab/P8#90]
Требуется выполнять Требования ТЗ: 
- работа под Windows 10, 
- Главное окно программы должно отображаться в полноэкранном режиме.
- Пользовательский интерфейс должен будет адаптируемым под экраны с различным разрешением.
- Должны поддерживаться экраны с разрешением не менее 640х480.

На данном этапе при запуске Программы наблюдается следующее:
При разрешении экрана 1600х900 размер окна (по диагонали) = 38см
При разрешении экрана 1920х1080 размер окна (по диагонали) = 32см
При разрешении экрана 1366х768 размер окна (по диагонали) превышает размеры самого экрана по высоте.

**Comment by ISPLab** [comment]
testdisplatresolution is wrong #115
